// Copyright 2016-2021 The Libsacloud Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by "stringer -type=ArchiveOSType"; DO NOT EDIT.

package ostype

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Custom-0]
	_ = x[CentOS-1]
	_ = x[CentOS8Stream-2]
	_ = x[CentOS8-3]
	_ = x[CentOS7-4]
	_ = x[AlmaLinux-5]
	_ = x[RockyLinux-6]
	_ = x[MiracleLinux-7]
	_ = x[Ubuntu-8]
	_ = x[Ubuntu2004-9]
	_ = x[Ubuntu1804-10]
	_ = x[Debian-11]
	_ = x[Debian10-12]
	_ = x[Debian11-13]
	_ = x[CoreOS-14]
	_ = x[RancherOS-15]
	_ = x[K3OS-16]
	_ = x[Kusanagi-17]
	_ = x[FreeBSD-18]
	_ = x[Windows2016-19]
	_ = x[Windows2016RDS-20]
	_ = x[Windows2016RDSOffice-21]
	_ = x[Windows2016SQLServerWeb-22]
	_ = x[Windows2016SQLServerStandard-23]
	_ = x[Windows2016SQLServer2017Standard-24]
	_ = x[Windows2016SQLServer2017Enterprise-25]
	_ = x[Windows2016SQLServerStandardAll-26]
	_ = x[Windows2016SQLServer2017StandardAll-27]
	_ = x[Windows2019-28]
	_ = x[Windows2019RDS-29]
	_ = x[Windows2019RDSOffice2019-30]
	_ = x[Windows2019SQLServer2017Web-31]
	_ = x[Windows2019SQLServer2019Web-32]
	_ = x[Windows2019SQLServer2017Standard-33]
	_ = x[Windows2019SQLServer2019Standard-34]
	_ = x[Windows2019SQLServer2017Enterprise-35]
	_ = x[Windows2019SQLServer2019Enterprise-36]
	_ = x[Windows2019SQLServer2017StandardAll-37]
	_ = x[Windows2019SQLServer2019StandardAll-38]
}

const _ArchiveOSType_name = "CustomCentOSCentOS8StreamCentOS8CentOS7AlmaLinuxRockyLinuxMiracleLinuxUbuntuUbuntu2004Ubuntu1804DebianDebian10Debian11CoreOSRancherOSK3OSKusanagiFreeBSDWindows2016Windows2016RDSWindows2016RDSOfficeWindows2016SQLServerWebWindows2016SQLServerStandardWindows2016SQLServer2017StandardWindows2016SQLServer2017EnterpriseWindows2016SQLServerStandardAllWindows2016SQLServer2017StandardAllWindows2019Windows2019RDSWindows2019RDSOffice2019Windows2019SQLServer2017WebWindows2019SQLServer2019WebWindows2019SQLServer2017StandardWindows2019SQLServer2019StandardWindows2019SQLServer2017EnterpriseWindows2019SQLServer2019EnterpriseWindows2019SQLServer2017StandardAllWindows2019SQLServer2019StandardAll"

var _ArchiveOSType_index = [...]uint16{0, 6, 12, 25, 32, 39, 48, 58, 70, 76, 86, 96, 102, 110, 118, 124, 133, 137, 145, 152, 163, 177, 197, 220, 248, 280, 314, 345, 380, 391, 405, 429, 456, 483, 515, 547, 581, 615, 650, 685}

func (i ArchiveOSType) String() string {
	if i < 0 || i >= ArchiveOSType(len(_ArchiveOSType_index)-1) {
		return "ArchiveOSType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ArchiveOSType_name[_ArchiveOSType_index[i]:_ArchiveOSType_index[i+1]]
}
