// Copyright 2016-2022 The Libsacloud Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by "stringer -type=ArchiveOSType"; DO NOT EDIT.

package ostype

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Custom-0]
	_ = x[CentOS-1]
	_ = x[CentOS8Stream-2]
	_ = x[CentOS7-3]
	_ = x[AlmaLinux-4]
	_ = x[RockyLinux-5]
	_ = x[MiracleLinux-6]
	_ = x[Ubuntu-7]
	_ = x[Ubuntu2004-8]
	_ = x[Ubuntu1804-9]
	_ = x[Debian-10]
	_ = x[Debian10-11]
	_ = x[Debian11-12]
	_ = x[CoreOS-13]
	_ = x[RancherOS-14]
	_ = x[K3OS-15]
	_ = x[Kusanagi-16]
	_ = x[FreeBSD-17]
	_ = x[Windows2016-18]
	_ = x[Windows2016RDS-19]
	_ = x[Windows2016RDSOffice-20]
	_ = x[Windows2016SQLServerWeb-21]
	_ = x[Windows2016SQLServerStandard-22]
	_ = x[Windows2016SQLServer2017Standard-23]
	_ = x[Windows2016SQLServer2017Enterprise-24]
	_ = x[Windows2016SQLServerStandardAll-25]
	_ = x[Windows2016SQLServer2017StandardAll-26]
	_ = x[Windows2019-27]
	_ = x[Windows2019RDS-28]
	_ = x[Windows2019RDSOffice2019-29]
	_ = x[Windows2019SQLServer2017Web-30]
	_ = x[Windows2019SQLServer2019Web-31]
	_ = x[Windows2019SQLServer2017Standard-32]
	_ = x[Windows2019SQLServer2019Standard-33]
	_ = x[Windows2019SQLServer2017Enterprise-34]
	_ = x[Windows2019SQLServer2019Enterprise-35]
	_ = x[Windows2019SQLServer2017StandardAll-36]
	_ = x[Windows2019SQLServer2019StandardAll-37]
}

const _ArchiveOSType_name = "CustomCentOSCentOS8StreamCentOS7AlmaLinuxRockyLinuxMiracleLinuxUbuntuUbuntu2004Ubuntu1804DebianDebian10Debian11CoreOSRancherOSK3OSKusanagiFreeBSDWindows2016Windows2016RDSWindows2016RDSOfficeWindows2016SQLServerWebWindows2016SQLServerStandardWindows2016SQLServer2017StandardWindows2016SQLServer2017EnterpriseWindows2016SQLServerStandardAllWindows2016SQLServer2017StandardAllWindows2019Windows2019RDSWindows2019RDSOffice2019Windows2019SQLServer2017WebWindows2019SQLServer2019WebWindows2019SQLServer2017StandardWindows2019SQLServer2019StandardWindows2019SQLServer2017EnterpriseWindows2019SQLServer2019EnterpriseWindows2019SQLServer2017StandardAllWindows2019SQLServer2019StandardAll"

var _ArchiveOSType_index = [...]uint16{0, 6, 12, 25, 32, 41, 51, 63, 69, 79, 89, 95, 103, 111, 117, 126, 130, 138, 145, 156, 170, 190, 213, 241, 273, 307, 338, 373, 384, 398, 422, 449, 476, 508, 540, 574, 608, 643, 678}

func (i ArchiveOSType) String() string {
	if i < 0 || i >= ArchiveOSType(len(_ArchiveOSType_index)-1) {
		return "ArchiveOSType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ArchiveOSType_name[_ArchiveOSType_index[i]:_ArchiveOSType_index[i+1]]
}
