// generated by 'github.com/sacloud/libsacloud/internal/tools/gen-api-meta'; DO NOT EDIT

package fake

const (
	// ResourceArchive is resource key of fake store
	ResourceArchive = "Archive"
	// ResourceBridge is resource key of fake store
	ResourceBridge = "Bridge"
	// ResourceCDROM is resource key of fake store
	ResourceCDROM = "CDROM"
	// ResourceDisk is resource key of fake store
	ResourceDisk = "Disk"
	// ResourceGSLB is resource key of fake store
	ResourceGSLB = "GSLB"
	// ResourceInterface is resource key of fake store
	ResourceInterface = "Interface"
	// ResourceInternet is resource key of fake store
	ResourceInternet = "Internet"
	// ResourceLoadBalancer is resource key of fake store
	ResourceLoadBalancer = "LoadBalancer"
	// ResourceNFS is resource key of fake store
	ResourceNFS = "NFS"
	// ResourceNote is resource key of fake store
	ResourceNote = "Note"
	// ResourcePacketFilter is resource key of fake store
	ResourcePacketFilter = "PacketFilter"
	// ResourceServer is resource key of fake store
	ResourceServer = "Server"
	// ResourceSIM is resource key of fake store
	ResourceSIM = "SIM"
	// ResourceSwitch is resource key of fake store
	ResourceSwitch = "Switch"
	// ResourceVPCRouter is resource key of fake store
	ResourceVPCRouter = "VPCRouter"
	// ResourceZone is resource key of fake store
	ResourceZone = "Zone"
)
