// generated by 'github.com/sacloud/libsacloud/internal/tools/gen-api-meta'; DO NOT EDIT

package fake

const (
	// ResourceArchive is resource key of fake store
	ResourceArchive = "Archive"
	// ResourceAuthStatus is resource key of fake store
	ResourceAuthStatus = "AuthStatus"
	// ResourceAutoBackup is resource key of fake store
	ResourceAutoBackup = "AutoBackup"
	// ResourceBill is resource key of fake store
	ResourceBill = "Bill"
	// ResourceBridge is resource key of fake store
	ResourceBridge = "Bridge"
	// ResourceCDROM is resource key of fake store
	ResourceCDROM = "CDROM"
	// ResourceCoupon is resource key of fake store
	ResourceCoupon = "Coupon"
	// ResourceDatabase is resource key of fake store
	ResourceDatabase = "Database"
	// ResourceDisk is resource key of fake store
	ResourceDisk = "Disk"
	// ResourceDiskPlan is resource key of fake store
	ResourceDiskPlan = "DiskPlan"
	// ResourceDNS is resource key of fake store
	ResourceDNS = "DNS"
	// ResourceGSLB is resource key of fake store
	ResourceGSLB = "GSLB"
	// ResourceIcon is resource key of fake store
	ResourceIcon = "Icon"
	// ResourceInterface is resource key of fake store
	ResourceInterface = "Interface"
	// ResourceInternet is resource key of fake store
	ResourceInternet = "Internet"
	// ResourceInternetPlan is resource key of fake store
	ResourceInternetPlan = "InternetPlan"
	// ResourceLicense is resource key of fake store
	ResourceLicense = "License"
	// ResourceLicenseInfo is resource key of fake store
	ResourceLicenseInfo = "LicenseInfo"
	// ResourceLoadBalancer is resource key of fake store
	ResourceLoadBalancer = "LoadBalancer"
	// ResourceNFS is resource key of fake store
	ResourceNFS = "NFS"
	// ResourceNote is resource key of fake store
	ResourceNote = "Note"
	// ResourcePacketFilter is resource key of fake store
	ResourcePacketFilter = "PacketFilter"
	// ResourcePrivateHost is resource key of fake store
	ResourcePrivateHost = "PrivateHost"
	// ResourcePrivateHostPlan is resource key of fake store
	ResourcePrivateHostPlan = "PrivateHostPlan"
	// ResourceProxyLB is resource key of fake store
	ResourceProxyLB = "ProxyLB"
	// ResourceRegion is resource key of fake store
	ResourceRegion = "Region"
	// ResourceServer is resource key of fake store
	ResourceServer = "Server"
	// ResourceServerPlan is resource key of fake store
	ResourceServerPlan = "ServerPlan"
	// ResourceSIM is resource key of fake store
	ResourceSIM = "SIM"
	// ResourceSimpleMonitor is resource key of fake store
	ResourceSimpleMonitor = "SimpleMonitor"
	// ResourceSSHKey is resource key of fake store
	ResourceSSHKey = "SSHKey"
	// ResourceSwitch is resource key of fake store
	ResourceSwitch = "Switch"
	// ResourceVPCRouter is resource key of fake store
	ResourceVPCRouter = "VPCRouter"
	// ResourceZone is resource key of fake store
	ResourceZone = "Zone"
)
