// Copyright 2016-2019 The Libsacloud Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by "stringer -type=UnixPublicArchiveType"; DO NOT EDIT.

package ostype

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CentOS-0]
	_ = x[CentOS6-1]
	_ = x[Ubuntu-2]
	_ = x[Debian-3]
	_ = x[CoreOS-4]
	_ = x[RancherOS-5]
	_ = x[K3OS-6]
	_ = x[Kusanagi-7]
	_ = x[FreeBSD-8]
}

const _UnixPublicArchiveType_name = "CentOSCentOS6UbuntuDebianCoreOSRancherOSK3OSKusanagiFreeBSD"

var _UnixPublicArchiveType_index = [...]uint8{0, 6, 13, 19, 25, 31, 40, 44, 52, 59}

func (i UnixPublicArchiveType) String() string {
	if i < 0 || i >= UnixPublicArchiveType(len(_UnixPublicArchiveType_index)-1) {
		return "UnixPublicArchiveType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _UnixPublicArchiveType_name[_UnixPublicArchiveType_index[i]:_UnixPublicArchiveType_index[i+1]]
}
