package keys

const (
	// ApplianceID .
	ApplianceID = "Appliance.ID"
	// Availability .
	Availability = "Availability"
	// BundleInfoHostClass .
	BundleInfoHostClass = "BundleInfo.HostClass"
	// BundleInfoID .
	BundleInfoID = "BundleInfo.ID"
	// BundleInfoName .
	BundleInfoName = "BundleInfo.Name"
	// DisplayOrder .
	DisplayOrder = "DisplayOrder"
	// HostName .
	HostName = "HostName"
	// InterfaceDriver .
	InterfaceDriver = "InterfaceDriver"
	// IconID .
	IconID = "Icon.ID"
	// IconScope .
	IconScope = "Icon.Scope"
	// IconName .
	IconName = "Icon.Name"
	// ID .
	ID = "ID"
	// Name .
	Name = "Name"
	// OriginalArchiveID ..ID
	OriginalArchiveID = "OriginalArchive.ID"
	// PlanID .
	PlanID = "Plan.ID"
	// PlanName .
	PlanName = "Plan.Name"
	// PrivateHostID .
	PrivateHostID = "PrivateHost.ID"
	// Scope .
	Scope = "Scope"
	// ServerPlanID .
	ServerPlanID = "ServerPlan.ID"
	// ServerPlanCPU .
	ServerPlanCPU = "ServerPlan.CPU"
	// ServerPlanCommitment .
	ServerPlanCommitment = "ServerPlan.Commitment"
	// ServerPlanName .
	ServerPlanName = "ServerPlan.Name"
	// ServerPlanGeneration .
	ServerPlanGeneration = "ServerPlan.Generation"
	// ServerPlanMemoryMB .
	ServerPlanMemoryMB = "ServerPlan.MemoryMB"
	// SizeMB .
	SizeMB = "SizeMB"
	// SourceArchiveID .
	SourceArchiveID = "SourceArchive.ID"
	// SourceDiskID .
	SourceDiskID = "SourceDisk.ID"
	// UserSubnetDefaultRoute .
	UserSubnetDefaultRoute = "UserSubnet.DefaultRoute"
	// UserSubnetNetworkMaskLen .
	UserSubnetNetworkMaskLen = "UserSubnet.NetworkMaskLen"
	// ZoneID .
	ZoneID = "Zone.ID"
)
