// generated by 'github.com/sacloud/libsacloud/internal/tools/gen-search-keys'; DO NOT EDIT

package keys

// FindArchive represents strong-typed filter keys for Archive.Find
var FindArchive = struct {
	Availability string
}{
	Availability: "Availability",
}
