// generated by 'github.com/sacloud/libsacloud/internal/tools/gen-api-envelope'; DO NOT EDIT

package sacloud

import (
	"time"

	"github.com/sacloud/libsacloud/v2/sacloud/naked"
	"github.com/sacloud/libsacloud/v2/sacloud/types"
)

// archiveFindRequestEnvelope is envelop of API request
type archiveFindRequestEnvelope struct {
	Count   int                    `json:",omitempty"`
	From    int                    `json:",omitempty"`
	Sort    []string               `json:",omitempty"`
	Filter  map[string]interface{} `json:",omitempty"`
	Include []string               `json:",omitempty"`
	Exclude []string               `json:",omitempty"`
}

// archiveFindResponseEnvelope is envelop of API response
type archiveFindResponseEnvelope struct {
	Total int `json:",omitempty"` // トータル件数
	From  int `json:",omitempty"` // ページング開始ページ
	Count int `json:",omitempty"` // 件数

	Archives []*naked.Archive `json:",omitempty"`
}

// archiveCreateRequestEnvelope is envelop of API request
type archiveCreateRequestEnvelope struct {
	Archive *naked.Archive `json:",omitempty"`
}

// archiveCreateResponseEnvelope is envelop of API response
type archiveCreateResponseEnvelope struct {
	IsOk    bool            `json:"is_ok,omitempty"` // is_ok項目
	Success types.APIResult `json:",omitempty"`      // success項目

	Archive *naked.Archive `json:",omitempty"`
}

// archiveCreateBlankRequestEnvelope is envelop of API request
type archiveCreateBlankRequestEnvelope struct {
	Archive *naked.Archive `json:",omitempty"`
}

// archiveCreateBlankResponseEnvelope is envelop of API response
type archiveCreateBlankResponseEnvelope struct {
	IsOk    bool            `json:"is_ok,omitempty"` // is_ok項目
	Success types.APIResult `json:",omitempty"`      // success項目

	Archive   *naked.Archive          `json:",omitempty"`
	FTPServer *naked.OpeningFTPServer `json:",omitempty"`
}

// archiveReadResponseEnvelope is envelop of API response
type archiveReadResponseEnvelope struct {
	IsOk    bool            `json:"is_ok,omitempty"` // is_ok項目
	Success types.APIResult `json:",omitempty"`      // success項目

	Archive *naked.Archive `json:",omitempty"`
}

// archiveUpdateRequestEnvelope is envelop of API request
type archiveUpdateRequestEnvelope struct {
	Archive *naked.Archive `json:",omitempty"`
}

// archiveUpdateResponseEnvelope is envelop of API response
type archiveUpdateResponseEnvelope struct {
	IsOk    bool            `json:"is_ok,omitempty"` // is_ok項目
	Success types.APIResult `json:",omitempty"`      // success項目

	Archive *naked.Archive `json:",omitempty"`
}

// archiveOpenFTPRequestEnvelope is envelop of API request
type archiveOpenFTPRequestEnvelope struct {
	ChangePassword bool `json:",omitempty"`
}

// archiveOpenFTPResponseEnvelope is envelop of API response
type archiveOpenFTPResponseEnvelope struct {
	IsOk    bool            `json:"is_ok,omitempty"` // is_ok項目
	Success types.APIResult `json:",omitempty"`      // success項目

	FTPServer *naked.OpeningFTPServer `json:",omitempty"`
}

// bridgeFindRequestEnvelope is envelop of API request
type bridgeFindRequestEnvelope struct {
	Count   int                    `json:",omitempty"`
	From    int                    `json:",omitempty"`
	Sort    []string               `json:",omitempty"`
	Filter  map[string]interface{} `json:",omitempty"`
	Include []string               `json:",omitempty"`
	Exclude []string               `json:",omitempty"`
}

// bridgeFindResponseEnvelope is envelop of API response
type bridgeFindResponseEnvelope struct {
	Total int `json:",omitempty"` // トータル件数
	From  int `json:",omitempty"` // ページング開始ページ
	Count int `json:",omitempty"` // 件数

	Bridges []*naked.Bridge `json:",omitempty"`
}

// bridgeCreateRequestEnvelope is envelop of API request
type bridgeCreateRequestEnvelope struct {
	Bridge *naked.Bridge `json:",omitempty"`
}

// bridgeCreateResponseEnvelope is envelop of API response
type bridgeCreateResponseEnvelope struct {
	IsOk    bool            `json:"is_ok,omitempty"` // is_ok項目
	Success types.APIResult `json:",omitempty"`      // success項目

	Bridge *naked.Bridge `json:",omitempty"`
}

// bridgeReadResponseEnvelope is envelop of API response
type bridgeReadResponseEnvelope struct {
	IsOk    bool            `json:"is_ok,omitempty"` // is_ok項目
	Success types.APIResult `json:",omitempty"`      // success項目

	Bridge *naked.Bridge `json:",omitempty"`
}

// bridgeUpdateRequestEnvelope is envelop of API request
type bridgeUpdateRequestEnvelope struct {
	Bridge *naked.Bridge `json:",omitempty"`
}

// bridgeUpdateResponseEnvelope is envelop of API response
type bridgeUpdateResponseEnvelope struct {
	IsOk    bool            `json:"is_ok,omitempty"` // is_ok項目
	Success types.APIResult `json:",omitempty"`      // success項目

	Bridge *naked.Bridge `json:",omitempty"`
}

// cdromFindRequestEnvelope is envelop of API request
type cdromFindRequestEnvelope struct {
	Count   int                    `json:",omitempty"`
	From    int                    `json:",omitempty"`
	Sort    []string               `json:",omitempty"`
	Filter  map[string]interface{} `json:",omitempty"`
	Include []string               `json:",omitempty"`
	Exclude []string               `json:",omitempty"`
}

// cdromFindResponseEnvelope is envelop of API response
type cdromFindResponseEnvelope struct {
	Total int `json:",omitempty"` // トータル件数
	From  int `json:",omitempty"` // ページング開始ページ
	Count int `json:",omitempty"` // 件数

	CDROMs []*naked.CDROM `json:",omitempty"`
}

// cdromCreateRequestEnvelope is envelop of API request
type cdromCreateRequestEnvelope struct {
	CDROM *naked.CDROM `json:",omitempty"`
}

// cdromCreateResponseEnvelope is envelop of API response
type cdromCreateResponseEnvelope struct {
	IsOk    bool            `json:"is_ok,omitempty"` // is_ok項目
	Success types.APIResult `json:",omitempty"`      // success項目

	CDROM     *naked.CDROM            `json:",omitempty"`
	FTPServer *naked.OpeningFTPServer `json:",omitempty"`
}

// cdromReadResponseEnvelope is envelop of API response
type cdromReadResponseEnvelope struct {
	IsOk    bool            `json:"is_ok,omitempty"` // is_ok項目
	Success types.APIResult `json:",omitempty"`      // success項目

	CDROM *naked.CDROM `json:",omitempty"`
}

// cdromUpdateRequestEnvelope is envelop of API request
type cdromUpdateRequestEnvelope struct {
	CDROM *naked.CDROM `json:",omitempty"`
}

// cdromUpdateResponseEnvelope is envelop of API response
type cdromUpdateResponseEnvelope struct {
	IsOk    bool            `json:"is_ok,omitempty"` // is_ok項目
	Success types.APIResult `json:",omitempty"`      // success項目

	CDROM *naked.CDROM `json:",omitempty"`
}

// cdromOpenFTPRequestEnvelope is envelop of API request
type cdromOpenFTPRequestEnvelope struct {
	ChangePassword bool `json:",omitempty"`
}

// cdromOpenFTPResponseEnvelope is envelop of API response
type cdromOpenFTPResponseEnvelope struct {
	IsOk    bool            `json:"is_ok,omitempty"` // is_ok項目
	Success types.APIResult `json:",omitempty"`      // success項目

	FTPServer *naked.OpeningFTPServer `json:",omitempty"`
}

// diskFindRequestEnvelope is envelop of API request
type diskFindRequestEnvelope struct {
	Count   int                    `json:",omitempty"`
	From    int                    `json:",omitempty"`
	Sort    []string               `json:",omitempty"`
	Filter  map[string]interface{} `json:",omitempty"`
	Include []string               `json:",omitempty"`
	Exclude []string               `json:",omitempty"`
}

// diskFindResponseEnvelope is envelop of API response
type diskFindResponseEnvelope struct {
	Total int `json:",omitempty"` // トータル件数
	From  int `json:",omitempty"` // ページング開始ページ
	Count int `json:",omitempty"` // 件数

	Disks []*naked.Disk `json:",omitempty"`
}

// diskCreateRequestEnvelope is envelop of API request
type diskCreateRequestEnvelope struct {
	Disk *naked.Disk `json:",omitempty"`
}

// diskCreateResponseEnvelope is envelop of API response
type diskCreateResponseEnvelope struct {
	IsOk    bool            `json:"is_ok,omitempty"` // is_ok項目
	Success types.APIResult `json:",omitempty"`      // success項目

	Disk *naked.Disk `json:",omitempty"`
}

// diskCreateDistantlyRequestEnvelope is envelop of API request
type diskCreateDistantlyRequestEnvelope struct {
	Disk        *naked.Disk `json:",omitempty"`
	DistantFrom []types.ID  `json:",omitempty"`
}

// diskCreateDistantlyResponseEnvelope is envelop of API response
type diskCreateDistantlyResponseEnvelope struct {
	IsOk    bool            `json:"is_ok,omitempty"` // is_ok項目
	Success types.APIResult `json:",omitempty"`      // success項目

	Disk *naked.Disk `json:",omitempty"`
}

// diskConfigRequestEnvelope is envelop of API request
type diskConfigRequestEnvelope struct {
	Password            string              `json:",omitempty"`
	SSHKey              *DiskEditSSHKey     `json:",omitempty"`
	SSHKeys             []*DiskEditSSHKey   `json:",omitempty"`
	DisablePWAuth       bool                `json:",omitempty"`
	EnableDHCP          bool                `json:",omitempty"`
	ChangePartitionUUID bool                `json:",omitempty"`
	HostName            string              `json:",omitempty"`
	Notes               []*DiskEditNote     `json:",omitempty"`
	UserIPAddress       string              `json:",omitempty"`
	UserSubnet          *DiskEditUserSubnet `json:",omitempty"`
}

// diskCreateWithConfigRequestEnvelope is envelop of API request
type diskCreateWithConfigRequestEnvelope struct {
	Disk            *naked.Disk     `json:",omitempty"`
	Config          *naked.DiskEdit `json:",omitempty"`
	BootAtAvailable bool            `json:",omitempty"`
}

// diskCreateWithConfigResponseEnvelope is envelop of API response
type diskCreateWithConfigResponseEnvelope struct {
	IsOk    bool            `json:"is_ok,omitempty"` // is_ok項目
	Success types.APIResult `json:",omitempty"`      // success項目

	Disk *naked.Disk `json:",omitempty"`
}

// diskCreateWithConfigDistantlyRequestEnvelope is envelop of API request
type diskCreateWithConfigDistantlyRequestEnvelope struct {
	Disk            *naked.Disk     `json:",omitempty"`
	Config          *naked.DiskEdit `json:",omitempty"`
	BootAtAvailable bool            `json:",omitempty"`
	DistantFrom     []types.ID      `json:",omitempty"`
}

// diskCreateWithConfigDistantlyResponseEnvelope is envelop of API response
type diskCreateWithConfigDistantlyResponseEnvelope struct {
	IsOk    bool            `json:"is_ok,omitempty"` // is_ok項目
	Success types.APIResult `json:",omitempty"`      // success項目

	Disk *naked.Disk `json:",omitempty"`
}

// diskInstallDistantFromRequestEnvelope is envelop of API request
type diskInstallDistantFromRequestEnvelope struct {
	Disk        *naked.Disk `json:",omitempty"`
	DistantFrom []types.ID  `json:",omitempty"`
}

// diskInstallDistantFromResponseEnvelope is envelop of API response
type diskInstallDistantFromResponseEnvelope struct {
	IsOk    bool            `json:"is_ok,omitempty"` // is_ok項目
	Success types.APIResult `json:",omitempty"`      // success項目

	Disk *naked.Disk `json:",omitempty"`
}

// diskInstallRequestEnvelope is envelop of API request
type diskInstallRequestEnvelope struct {
	Disk *naked.Disk `json:",omitempty"`
}

// diskInstallResponseEnvelope is envelop of API response
type diskInstallResponseEnvelope struct {
	IsOk    bool            `json:"is_ok,omitempty"` // is_ok項目
	Success types.APIResult `json:",omitempty"`      // success項目

	Disk *naked.Disk `json:",omitempty"`
}

// diskReadResponseEnvelope is envelop of API response
type diskReadResponseEnvelope struct {
	IsOk    bool            `json:"is_ok,omitempty"` // is_ok項目
	Success types.APIResult `json:",omitempty"`      // success項目

	Disk *naked.Disk `json:",omitempty"`
}

// diskUpdateRequestEnvelope is envelop of API request
type diskUpdateRequestEnvelope struct {
	Disk *naked.Disk `json:",omitempty"`
}

// diskUpdateResponseEnvelope is envelop of API response
type diskUpdateResponseEnvelope struct {
	IsOk    bool            `json:"is_ok,omitempty"` // is_ok項目
	Success types.APIResult `json:",omitempty"`      // success項目

	Disk *naked.Disk `json:",omitempty"`
}

// diskMonitorRequestEnvelope is envelop of API request
type diskMonitorRequestEnvelope struct {
	Start time.Time `json:",omitempty"`
	End   time.Time `json:",omitempty"`
}

// diskMonitorResponseEnvelope is envelop of API response
type diskMonitorResponseEnvelope struct {
	IsOk    bool            `json:"is_ok,omitempty"` // is_ok項目
	Success types.APIResult `json:",omitempty"`      // success項目

	Data *naked.MonitorValues `json:",omitempty"`
}

// gslbFindRequestEnvelope is envelop of API request
type gslbFindRequestEnvelope struct {
	Count   int                    `json:",omitempty"`
	From    int                    `json:",omitempty"`
	Sort    []string               `json:",omitempty"`
	Filter  map[string]interface{} `json:",omitempty"`
	Include []string               `json:",omitempty"`
	Exclude []string               `json:",omitempty"`
}

// gslbFindResponseEnvelope is envelop of API response
type gslbFindResponseEnvelope struct {
	Total int `json:",omitempty"` // トータル件数
	From  int `json:",omitempty"` // ページング開始ページ
	Count int `json:",omitempty"` // 件数

	CommonServiceItems []*naked.GSLB `json:",omitempty"`
}

// gslbCreateRequestEnvelope is envelop of API request
type gslbCreateRequestEnvelope struct {
	CommonServiceItem *naked.GSLB `json:",omitempty"`
}

// gslbCreateResponseEnvelope is envelop of API response
type gslbCreateResponseEnvelope struct {
	IsOk    bool            `json:"is_ok,omitempty"` // is_ok項目
	Success types.APIResult `json:",omitempty"`      // success項目

	CommonServiceItem *naked.GSLB `json:",omitempty"`
}

// gslbReadResponseEnvelope is envelop of API response
type gslbReadResponseEnvelope struct {
	IsOk    bool            `json:"is_ok,omitempty"` // is_ok項目
	Success types.APIResult `json:",omitempty"`      // success項目

	CommonServiceItem *naked.GSLB `json:",omitempty"`
}

// gslbUpdateRequestEnvelope is envelop of API request
type gslbUpdateRequestEnvelope struct {
	CommonServiceItem *naked.GSLB `json:",omitempty"`
}

// gslbUpdateResponseEnvelope is envelop of API response
type gslbUpdateResponseEnvelope struct {
	IsOk    bool            `json:"is_ok,omitempty"` // is_ok項目
	Success types.APIResult `json:",omitempty"`      // success項目

	CommonServiceItem *naked.GSLB `json:",omitempty"`
}

// interfaceFindRequestEnvelope is envelop of API request
type interfaceFindRequestEnvelope struct {
	Count   int                    `json:",omitempty"`
	From    int                    `json:",omitempty"`
	Sort    []string               `json:",omitempty"`
	Filter  map[string]interface{} `json:",omitempty"`
	Include []string               `json:",omitempty"`
	Exclude []string               `json:",omitempty"`
}

// interfaceFindResponseEnvelope is envelop of API response
type interfaceFindResponseEnvelope struct {
	Total int `json:",omitempty"` // トータル件数
	From  int `json:",omitempty"` // ページング開始ページ
	Count int `json:",omitempty"` // 件数

	Interfaces []*naked.Interface `json:",omitempty"`
}

// interfaceCreateRequestEnvelope is envelop of API request
type interfaceCreateRequestEnvelope struct {
	Interface *naked.Interface `json:",omitempty"`
}

// interfaceCreateResponseEnvelope is envelop of API response
type interfaceCreateResponseEnvelope struct {
	IsOk    bool            `json:"is_ok,omitempty"` // is_ok項目
	Success types.APIResult `json:",omitempty"`      // success項目

	Interface *naked.Interface `json:",omitempty"`
}

// interfaceReadResponseEnvelope is envelop of API response
type interfaceReadResponseEnvelope struct {
	IsOk    bool            `json:"is_ok,omitempty"` // is_ok項目
	Success types.APIResult `json:",omitempty"`      // success項目

	Interface *naked.Interface `json:",omitempty"`
}

// interfaceUpdateRequestEnvelope is envelop of API request
type interfaceUpdateRequestEnvelope struct {
	Interface *naked.Interface `json:",omitempty"`
}

// interfaceUpdateResponseEnvelope is envelop of API response
type interfaceUpdateResponseEnvelope struct {
	IsOk    bool            `json:"is_ok,omitempty"` // is_ok項目
	Success types.APIResult `json:",omitempty"`      // success項目

	Interface *naked.Interface `json:",omitempty"`
}

// interfaceMonitorRequestEnvelope is envelop of API request
type interfaceMonitorRequestEnvelope struct {
	Start time.Time `json:",omitempty"`
	End   time.Time `json:",omitempty"`
}

// interfaceMonitorResponseEnvelope is envelop of API response
type interfaceMonitorResponseEnvelope struct {
	IsOk    bool            `json:"is_ok,omitempty"` // is_ok項目
	Success types.APIResult `json:",omitempty"`      // success項目

	Data *naked.MonitorValues `json:",omitempty"`
}

// internetFindRequestEnvelope is envelop of API request
type internetFindRequestEnvelope struct {
	Count   int                    `json:",omitempty"`
	From    int                    `json:",omitempty"`
	Sort    []string               `json:",omitempty"`
	Filter  map[string]interface{} `json:",omitempty"`
	Include []string               `json:",omitempty"`
	Exclude []string               `json:",omitempty"`
}

// internetFindResponseEnvelope is envelop of API response
type internetFindResponseEnvelope struct {
	Total int `json:",omitempty"` // トータル件数
	From  int `json:",omitempty"` // ページング開始ページ
	Count int `json:",omitempty"` // 件数

	Internets []*naked.Internet `json:",omitempty"`
}

// internetCreateRequestEnvelope is envelop of API request
type internetCreateRequestEnvelope struct {
	Internet *naked.Internet `json:",omitempty"`
}

// internetCreateResponseEnvelope is envelop of API response
type internetCreateResponseEnvelope struct {
	IsOk    bool            `json:"is_ok,omitempty"` // is_ok項目
	Success types.APIResult `json:",omitempty"`      // success項目

	Internet *naked.Internet `json:",omitempty"`
}

// internetReadResponseEnvelope is envelop of API response
type internetReadResponseEnvelope struct {
	IsOk    bool            `json:"is_ok,omitempty"` // is_ok項目
	Success types.APIResult `json:",omitempty"`      // success項目

	Internet *naked.Internet `json:",omitempty"`
}

// internetUpdateRequestEnvelope is envelop of API request
type internetUpdateRequestEnvelope struct {
	Internet *naked.Internet `json:",omitempty"`
}

// internetUpdateResponseEnvelope is envelop of API response
type internetUpdateResponseEnvelope struct {
	IsOk    bool            `json:"is_ok,omitempty"` // is_ok項目
	Success types.APIResult `json:",omitempty"`      // success項目

	Internet *naked.Internet `json:",omitempty"`
}

// internetUpdateBandWidthRequestEnvelope is envelop of API request
type internetUpdateBandWidthRequestEnvelope struct {
	Internet *naked.Internet `json:",omitempty"`
}

// internetUpdateBandWidthResponseEnvelope is envelop of API response
type internetUpdateBandWidthResponseEnvelope struct {
	IsOk    bool            `json:"is_ok,omitempty"` // is_ok項目
	Success types.APIResult `json:",omitempty"`      // success項目

	Internet *naked.Internet `json:",omitempty"`
}

// internetAddSubnetRequestEnvelope is envelop of API request
type internetAddSubnetRequestEnvelope struct {
	NetworkMaskLen int    `json:",omitempty"`
	NextHop        string `json:",omitempty"`
}

// internetAddSubnetResponseEnvelope is envelop of API response
type internetAddSubnetResponseEnvelope struct {
	IsOk    bool            `json:"is_ok,omitempty"` // is_ok項目
	Success types.APIResult `json:",omitempty"`      // success項目

	Subnet *naked.Subnet `json:",omitempty"`
}

// internetUpdateSubnetRequestEnvelope is envelop of API request
type internetUpdateSubnetRequestEnvelope struct {
	NextHop string `json:",omitempty"`
}

// internetUpdateSubnetResponseEnvelope is envelop of API response
type internetUpdateSubnetResponseEnvelope struct {
	IsOk    bool            `json:"is_ok,omitempty"` // is_ok項目
	Success types.APIResult `json:",omitempty"`      // success項目

	Subnet *naked.Subnet `json:",omitempty"`
}

// internetMonitorRequestEnvelope is envelop of API request
type internetMonitorRequestEnvelope struct {
	Start time.Time `json:",omitempty"`
	End   time.Time `json:",omitempty"`
}

// internetMonitorResponseEnvelope is envelop of API response
type internetMonitorResponseEnvelope struct {
	IsOk    bool            `json:"is_ok,omitempty"` // is_ok項目
	Success types.APIResult `json:",omitempty"`      // success項目

	Data *naked.MonitorValues `json:",omitempty"`
}

// loadbalancerFindRequestEnvelope is envelop of API request
type loadbalancerFindRequestEnvelope struct {
	Count   int                    `json:",omitempty"`
	From    int                    `json:",omitempty"`
	Sort    []string               `json:",omitempty"`
	Filter  map[string]interface{} `json:",omitempty"`
	Include []string               `json:",omitempty"`
	Exclude []string               `json:",omitempty"`
}

// loadbalancerFindResponseEnvelope is envelop of API response
type loadbalancerFindResponseEnvelope struct {
	Total int `json:",omitempty"` // トータル件数
	From  int `json:",omitempty"` // ページング開始ページ
	Count int `json:",omitempty"` // 件数

	Appliances []*naked.LoadBalancer `json:",omitempty"`
}

// loadbalancerCreateRequestEnvelope is envelop of API request
type loadbalancerCreateRequestEnvelope struct {
	Appliance *naked.LoadBalancer `json:",omitempty"`
}

// loadbalancerCreateResponseEnvelope is envelop of API response
type loadbalancerCreateResponseEnvelope struct {
	IsOk    bool            `json:"is_ok,omitempty"` // is_ok項目
	Success types.APIResult `json:",omitempty"`      // success項目

	Appliance *naked.LoadBalancer `json:",omitempty"`
}

// loadbalancerReadResponseEnvelope is envelop of API response
type loadbalancerReadResponseEnvelope struct {
	IsOk    bool            `json:"is_ok,omitempty"` // is_ok項目
	Success types.APIResult `json:",omitempty"`      // success項目

	Appliance *naked.LoadBalancer `json:",omitempty"`
}

// loadbalancerUpdateRequestEnvelope is envelop of API request
type loadbalancerUpdateRequestEnvelope struct {
	Appliance *naked.LoadBalancer `json:",omitempty"`
}

// loadbalancerUpdateResponseEnvelope is envelop of API response
type loadbalancerUpdateResponseEnvelope struct {
	IsOk    bool            `json:"is_ok,omitempty"` // is_ok項目
	Success types.APIResult `json:",omitempty"`      // success項目

	Appliance *naked.LoadBalancer `json:",omitempty"`
}

// loadbalancerShutdownRequestEnvelope is envelop of API request
type loadbalancerShutdownRequestEnvelope struct {
	Force bool `json:",omitempty"`
}

// loadbalancerMonitorInterfaceRequestEnvelope is envelop of API request
type loadbalancerMonitorInterfaceRequestEnvelope struct {
	Start time.Time `json:",omitempty"`
	End   time.Time `json:",omitempty"`
}

// loadbalancerMonitorInterfaceResponseEnvelope is envelop of API response
type loadbalancerMonitorInterfaceResponseEnvelope struct {
	IsOk    bool            `json:"is_ok,omitempty"` // is_ok項目
	Success types.APIResult `json:",omitempty"`      // success項目

	Data *naked.MonitorValues `json:",omitempty"`
}

// loadbalancerStatusResponseEnvelope is envelop of API response
type loadbalancerStatusResponseEnvelope struct {
	Total int `json:",omitempty"` // トータル件数
	From  int `json:",omitempty"` // ページング開始ページ
	Count int `json:",omitempty"` // 件数

	LoadBalancer []*naked.LoadBalancerStatus `json:",omitempty"`
}

// nfsFindRequestEnvelope is envelop of API request
type nfsFindRequestEnvelope struct {
	Count   int                    `json:",omitempty"`
	From    int                    `json:",omitempty"`
	Sort    []string               `json:",omitempty"`
	Filter  map[string]interface{} `json:",omitempty"`
	Include []string               `json:",omitempty"`
	Exclude []string               `json:",omitempty"`
}

// nfsFindResponseEnvelope is envelop of API response
type nfsFindResponseEnvelope struct {
	Total int `json:",omitempty"` // トータル件数
	From  int `json:",omitempty"` // ページング開始ページ
	Count int `json:",omitempty"` // 件数

	Appliances []*naked.NFS `json:",omitempty"`
}

// nfsCreateRequestEnvelope is envelop of API request
type nfsCreateRequestEnvelope struct {
	Appliance *naked.NFS `json:",omitempty"`
}

// nfsCreateResponseEnvelope is envelop of API response
type nfsCreateResponseEnvelope struct {
	IsOk    bool            `json:"is_ok,omitempty"` // is_ok項目
	Success types.APIResult `json:",omitempty"`      // success項目

	Appliance *naked.NFS `json:",omitempty"`
}

// nfsReadResponseEnvelope is envelop of API response
type nfsReadResponseEnvelope struct {
	IsOk    bool            `json:"is_ok,omitempty"` // is_ok項目
	Success types.APIResult `json:",omitempty"`      // success項目

	Appliance *naked.NFS `json:",omitempty"`
}

// nfsUpdateRequestEnvelope is envelop of API request
type nfsUpdateRequestEnvelope struct {
	Appliance *naked.NFS `json:",omitempty"`
}

// nfsUpdateResponseEnvelope is envelop of API response
type nfsUpdateResponseEnvelope struct {
	IsOk    bool            `json:"is_ok,omitempty"` // is_ok項目
	Success types.APIResult `json:",omitempty"`      // success項目

	Appliance *naked.NFS `json:",omitempty"`
}

// nfsShutdownRequestEnvelope is envelop of API request
type nfsShutdownRequestEnvelope struct {
	Force bool `json:",omitempty"`
}

// nfsMonitorFreeDiskSizeRequestEnvelope is envelop of API request
type nfsMonitorFreeDiskSizeRequestEnvelope struct {
	Start time.Time `json:",omitempty"`
	End   time.Time `json:",omitempty"`
}

// nfsMonitorFreeDiskSizeResponseEnvelope is envelop of API response
type nfsMonitorFreeDiskSizeResponseEnvelope struct {
	IsOk    bool            `json:"is_ok,omitempty"` // is_ok項目
	Success types.APIResult `json:",omitempty"`      // success項目

	Data *naked.MonitorValues `json:",omitempty"`
}

// nfsMonitorInterfaceRequestEnvelope is envelop of API request
type nfsMonitorInterfaceRequestEnvelope struct {
	Start time.Time `json:",omitempty"`
	End   time.Time `json:",omitempty"`
}

// nfsMonitorInterfaceResponseEnvelope is envelop of API response
type nfsMonitorInterfaceResponseEnvelope struct {
	IsOk    bool            `json:"is_ok,omitempty"` // is_ok項目
	Success types.APIResult `json:",omitempty"`      // success項目

	Data *naked.MonitorValues `json:",omitempty"`
}

// noteFindRequestEnvelope is envelop of API request
type noteFindRequestEnvelope struct {
	Count   int                    `json:",omitempty"`
	From    int                    `json:",omitempty"`
	Sort    []string               `json:",omitempty"`
	Filter  map[string]interface{} `json:",omitempty"`
	Include []string               `json:",omitempty"`
	Exclude []string               `json:",omitempty"`
}

// noteFindResponseEnvelope is envelop of API response
type noteFindResponseEnvelope struct {
	Total int `json:",omitempty"` // トータル件数
	From  int `json:",omitempty"` // ページング開始ページ
	Count int `json:",omitempty"` // 件数

	Notes []*naked.Note `json:",omitempty"`
}

// noteCreateRequestEnvelope is envelop of API request
type noteCreateRequestEnvelope struct {
	Note *naked.Note `json:",omitempty"`
}

// noteCreateResponseEnvelope is envelop of API response
type noteCreateResponseEnvelope struct {
	IsOk    bool            `json:"is_ok,omitempty"` // is_ok項目
	Success types.APIResult `json:",omitempty"`      // success項目

	Note *naked.Note `json:",omitempty"`
}

// noteReadResponseEnvelope is envelop of API response
type noteReadResponseEnvelope struct {
	IsOk    bool            `json:"is_ok,omitempty"` // is_ok項目
	Success types.APIResult `json:",omitempty"`      // success項目

	Note *naked.Note `json:",omitempty"`
}

// noteUpdateRequestEnvelope is envelop of API request
type noteUpdateRequestEnvelope struct {
	Note *naked.Note `json:",omitempty"`
}

// noteUpdateResponseEnvelope is envelop of API response
type noteUpdateResponseEnvelope struct {
	IsOk    bool            `json:"is_ok,omitempty"` // is_ok項目
	Success types.APIResult `json:",omitempty"`      // success項目

	Note *naked.Note `json:",omitempty"`
}

// packetfilterFindRequestEnvelope is envelop of API request
type packetfilterFindRequestEnvelope struct {
	Count   int                    `json:",omitempty"`
	From    int                    `json:",omitempty"`
	Sort    []string               `json:",omitempty"`
	Filter  map[string]interface{} `json:",omitempty"`
	Include []string               `json:",omitempty"`
	Exclude []string               `json:",omitempty"`
}

// packetfilterFindResponseEnvelope is envelop of API response
type packetfilterFindResponseEnvelope struct {
	Total int `json:",omitempty"` // トータル件数
	From  int `json:",omitempty"` // ページング開始ページ
	Count int `json:",omitempty"` // 件数

	PacketFilters []*naked.PacketFilter `json:",omitempty"`
}

// packetfilterCreateRequestEnvelope is envelop of API request
type packetfilterCreateRequestEnvelope struct {
	PacketFilter *naked.PacketFilter `json:",omitempty"`
}

// packetfilterCreateResponseEnvelope is envelop of API response
type packetfilterCreateResponseEnvelope struct {
	IsOk    bool            `json:"is_ok,omitempty"` // is_ok項目
	Success types.APIResult `json:",omitempty"`      // success項目

	PacketFilter *naked.PacketFilter `json:",omitempty"`
}

// packetfilterReadResponseEnvelope is envelop of API response
type packetfilterReadResponseEnvelope struct {
	IsOk    bool            `json:"is_ok,omitempty"` // is_ok項目
	Success types.APIResult `json:",omitempty"`      // success項目

	PacketFilter *naked.PacketFilter `json:",omitempty"`
}

// packetfilterUpdateRequestEnvelope is envelop of API request
type packetfilterUpdateRequestEnvelope struct {
	PacketFilter *naked.PacketFilter `json:",omitempty"`
}

// packetfilterUpdateResponseEnvelope is envelop of API response
type packetfilterUpdateResponseEnvelope struct {
	IsOk    bool            `json:"is_ok,omitempty"` // is_ok項目
	Success types.APIResult `json:",omitempty"`      // success項目

	PacketFilter *naked.PacketFilter `json:",omitempty"`
}

// serverFindRequestEnvelope is envelop of API request
type serverFindRequestEnvelope struct {
	Count   int                    `json:",omitempty"`
	From    int                    `json:",omitempty"`
	Sort    []string               `json:",omitempty"`
	Filter  map[string]interface{} `json:",omitempty"`
	Include []string               `json:",omitempty"`
	Exclude []string               `json:",omitempty"`
}

// serverFindResponseEnvelope is envelop of API response
type serverFindResponseEnvelope struct {
	Total int `json:",omitempty"` // トータル件数
	From  int `json:",omitempty"` // ページング開始ページ
	Count int `json:",omitempty"` // 件数

	Servers []*naked.Server `json:",omitempty"`
}

// serverCreateRequestEnvelope is envelop of API request
type serverCreateRequestEnvelope struct {
	Server *naked.Server `json:",omitempty"`
}

// serverCreateResponseEnvelope is envelop of API response
type serverCreateResponseEnvelope struct {
	IsOk    bool            `json:"is_ok,omitempty"` // is_ok項目
	Success types.APIResult `json:",omitempty"`      // success項目

	Server *naked.Server `json:",omitempty"`
}

// serverReadResponseEnvelope is envelop of API response
type serverReadResponseEnvelope struct {
	IsOk    bool            `json:"is_ok,omitempty"` // is_ok項目
	Success types.APIResult `json:",omitempty"`      // success項目

	Server *naked.Server `json:",omitempty"`
}

// serverUpdateRequestEnvelope is envelop of API request
type serverUpdateRequestEnvelope struct {
	Server *naked.Server `json:",omitempty"`
}

// serverUpdateResponseEnvelope is envelop of API response
type serverUpdateResponseEnvelope struct {
	IsOk    bool            `json:"is_ok,omitempty"` // is_ok項目
	Success types.APIResult `json:",omitempty"`      // success項目

	Server *naked.Server `json:",omitempty"`
}

// serverChangePlanRequestEnvelope is envelop of API request
type serverChangePlanRequestEnvelope struct {
	CPU                  int                   `json:",omitempty"`
	MemoryMB             int                   `json:",omitempty"`
	ServerPlanGeneration types.EPlanGeneration `json:",omitempty"`
	ServerPlanCommitment types.ECommitment     `json:",omitempty"`
}

// serverChangePlanResponseEnvelope is envelop of API response
type serverChangePlanResponseEnvelope struct {
	IsOk    bool            `json:"is_ok,omitempty"` // is_ok項目
	Success types.APIResult `json:",omitempty"`      // success項目

	Server *naked.Server `json:",omitempty"`
}

// serverInsertCDROMRequestEnvelope is envelop of API request
type serverInsertCDROMRequestEnvelope struct {
	CDROM *naked.CDROM `json:",omitempty"`
}

// serverEjectCDROMRequestEnvelope is envelop of API request
type serverEjectCDROMRequestEnvelope struct {
	CDROM *naked.CDROM `json:",omitempty"`
}

// serverShutdownRequestEnvelope is envelop of API request
type serverShutdownRequestEnvelope struct {
	Force bool `json:",omitempty"`
}

// serverMonitorRequestEnvelope is envelop of API request
type serverMonitorRequestEnvelope struct {
	Start time.Time `json:",omitempty"`
	End   time.Time `json:",omitempty"`
}

// serverMonitorResponseEnvelope is envelop of API response
type serverMonitorResponseEnvelope struct {
	IsOk    bool            `json:"is_ok,omitempty"` // is_ok項目
	Success types.APIResult `json:",omitempty"`      // success項目

	Data *naked.MonitorValues `json:",omitempty"`
}

// simFindRequestEnvelope is envelop of API request
type simFindRequestEnvelope struct {
	Count   int                    `json:",omitempty"`
	From    int                    `json:",omitempty"`
	Sort    []string               `json:",omitempty"`
	Filter  map[string]interface{} `json:",omitempty"`
	Include []string               `json:",omitempty"`
	Exclude []string               `json:",omitempty"`
}

// simFindResponseEnvelope is envelop of API response
type simFindResponseEnvelope struct {
	Total int `json:",omitempty"` // トータル件数
	From  int `json:",omitempty"` // ページング開始ページ
	Count int `json:",omitempty"` // 件数

	CommonServiceItems []*naked.SIM `json:",omitempty"`
}

// simCreateRequestEnvelope is envelop of API request
type simCreateRequestEnvelope struct {
	CommonServiceItem *naked.SIM `json:",omitempty"`
}

// simCreateResponseEnvelope is envelop of API response
type simCreateResponseEnvelope struct {
	IsOk    bool            `json:"is_ok,omitempty"` // is_ok項目
	Success types.APIResult `json:",omitempty"`      // success項目

	CommonServiceItem *naked.SIM `json:",omitempty"`
}

// simReadResponseEnvelope is envelop of API response
type simReadResponseEnvelope struct {
	IsOk    bool            `json:"is_ok,omitempty"` // is_ok項目
	Success types.APIResult `json:",omitempty"`      // success項目

	CommonServiceItem *naked.SIM `json:",omitempty"`
}

// simUpdateRequestEnvelope is envelop of API request
type simUpdateRequestEnvelope struct {
	CommonServiceItem *naked.SIM `json:",omitempty"`
}

// simUpdateResponseEnvelope is envelop of API response
type simUpdateResponseEnvelope struct {
	IsOk    bool            `json:"is_ok,omitempty"` // is_ok項目
	Success types.APIResult `json:",omitempty"`      // success項目

	CommonServiceItem *naked.SIM `json:",omitempty"`
}

// simAssignIPRequestEnvelope is envelop of API request
type simAssignIPRequestEnvelope struct {
	SIM *naked.SIMAssignIPRequest `json:"sim"`
}

// simIMEILockRequestEnvelope is envelop of API request
type simIMEILockRequestEnvelope struct {
	SIM *naked.SIMIMEILockRequest `json:"sim"`
}

// simLogsResponseEnvelope is envelop of API response
type simLogsResponseEnvelope struct {
	Total int `json:",omitempty"` // トータル件数
	From  int `json:",omitempty"` // ページング開始ページ
	Count int `json:",omitempty"` // 件数

	Logs []*naked.SIMLog `json:",omitempty"`
}

// simGetNetworkOperatorResponseEnvelope is envelop of API response
type simGetNetworkOperatorResponseEnvelope struct {
	Total int `json:",omitempty"` // トータル件数
	From  int `json:",omitempty"` // ページング開始ページ
	Count int `json:",omitempty"` // 件数

	NetworkOperationConfigs []*naked.SIMNetworkOperatorConfig `json:",omitempty"`
}

// simSetNetworkOperatorRequestEnvelope is envelop of API request
type simSetNetworkOperatorRequestEnvelope struct {
	NetworkOperatorConfigs []*SIMNetworkOperatorConfig `json:",omitempty"`
}

// simMonitorSIMRequestEnvelope is envelop of API request
type simMonitorSIMRequestEnvelope struct {
	Start time.Time `json:",omitempty"`
	End   time.Time `json:",omitempty"`
}

// simMonitorSIMResponseEnvelope is envelop of API response
type simMonitorSIMResponseEnvelope struct {
	IsOk    bool            `json:"is_ok,omitempty"` // is_ok項目
	Success types.APIResult `json:",omitempty"`      // success項目

	Data *naked.MonitorValues `json:",omitempty"`
}

// switchFindRequestEnvelope is envelop of API request
type switchFindRequestEnvelope struct {
	Count   int                    `json:",omitempty"`
	From    int                    `json:",omitempty"`
	Sort    []string               `json:",omitempty"`
	Filter  map[string]interface{} `json:",omitempty"`
	Include []string               `json:",omitempty"`
	Exclude []string               `json:",omitempty"`
}

// switchFindResponseEnvelope is envelop of API response
type switchFindResponseEnvelope struct {
	Total int `json:",omitempty"` // トータル件数
	From  int `json:",omitempty"` // ページング開始ページ
	Count int `json:",omitempty"` // 件数

	Switches []*naked.Switch `json:",omitempty"`
}

// switchCreateRequestEnvelope is envelop of API request
type switchCreateRequestEnvelope struct {
	Switch *naked.Switch `json:",omitempty"`
}

// switchCreateResponseEnvelope is envelop of API response
type switchCreateResponseEnvelope struct {
	IsOk    bool            `json:"is_ok,omitempty"` // is_ok項目
	Success types.APIResult `json:",omitempty"`      // success項目

	Switch *naked.Switch `json:",omitempty"`
}

// switchReadResponseEnvelope is envelop of API response
type switchReadResponseEnvelope struct {
	IsOk    bool            `json:"is_ok,omitempty"` // is_ok項目
	Success types.APIResult `json:",omitempty"`      // success項目

	Switch *naked.Switch `json:",omitempty"`
}

// switchUpdateRequestEnvelope is envelop of API request
type switchUpdateRequestEnvelope struct {
	Switch *naked.Switch `json:",omitempty"`
}

// switchUpdateResponseEnvelope is envelop of API response
type switchUpdateResponseEnvelope struct {
	IsOk    bool            `json:"is_ok,omitempty"` // is_ok項目
	Success types.APIResult `json:",omitempty"`      // success項目

	Switch *naked.Switch `json:",omitempty"`
}

// vpcrouterFindRequestEnvelope is envelop of API request
type vpcrouterFindRequestEnvelope struct {
	Count   int                    `json:",omitempty"`
	From    int                    `json:",omitempty"`
	Sort    []string               `json:",omitempty"`
	Filter  map[string]interface{} `json:",omitempty"`
	Include []string               `json:",omitempty"`
	Exclude []string               `json:",omitempty"`
}

// vpcrouterFindResponseEnvelope is envelop of API response
type vpcrouterFindResponseEnvelope struct {
	Total int `json:",omitempty"` // トータル件数
	From  int `json:",omitempty"` // ページング開始ページ
	Count int `json:",omitempty"` // 件数

	Appliances []*naked.VPCRouter `json:",omitempty"`
}

// vpcrouterCreateRequestEnvelope is envelop of API request
type vpcrouterCreateRequestEnvelope struct {
	Appliance *naked.VPCRouter `json:",omitempty"`
}

// vpcrouterCreateResponseEnvelope is envelop of API response
type vpcrouterCreateResponseEnvelope struct {
	IsOk    bool            `json:"is_ok,omitempty"` // is_ok項目
	Success types.APIResult `json:",omitempty"`      // success項目

	Appliance *naked.VPCRouter `json:",omitempty"`
}

// vpcrouterReadResponseEnvelope is envelop of API response
type vpcrouterReadResponseEnvelope struct {
	IsOk    bool            `json:"is_ok,omitempty"` // is_ok項目
	Success types.APIResult `json:",omitempty"`      // success項目

	Appliance *naked.VPCRouter `json:",omitempty"`
}

// vpcrouterUpdateRequestEnvelope is envelop of API request
type vpcrouterUpdateRequestEnvelope struct {
	Appliance *naked.VPCRouter `json:",omitempty"`
}

// vpcrouterUpdateResponseEnvelope is envelop of API response
type vpcrouterUpdateResponseEnvelope struct {
	IsOk    bool            `json:"is_ok,omitempty"` // is_ok項目
	Success types.APIResult `json:",omitempty"`      // success項目

	Appliance *naked.VPCRouter `json:",omitempty"`
}

// vpcrouterShutdownRequestEnvelope is envelop of API request
type vpcrouterShutdownRequestEnvelope struct {
	Force bool `json:",omitempty"`
}

// vpcrouterMonitorInterfaceRequestEnvelope is envelop of API request
type vpcrouterMonitorInterfaceRequestEnvelope struct {
	Start time.Time `json:",omitempty"`
	End   time.Time `json:",omitempty"`
}

// vpcrouterMonitorInterfaceResponseEnvelope is envelop of API response
type vpcrouterMonitorInterfaceResponseEnvelope struct {
	IsOk    bool            `json:"is_ok,omitempty"` // is_ok項目
	Success types.APIResult `json:",omitempty"`      // success項目

	Data *naked.MonitorValues `json:",omitempty"`
}

// zoneFindRequestEnvelope is envelop of API request
type zoneFindRequestEnvelope struct {
	Count   int                    `json:",omitempty"`
	From    int                    `json:",omitempty"`
	Sort    []string               `json:",omitempty"`
	Filter  map[string]interface{} `json:",omitempty"`
	Include []string               `json:",omitempty"`
	Exclude []string               `json:",omitempty"`
}

// zoneFindResponseEnvelope is envelop of API response
type zoneFindResponseEnvelope struct {
	Total int `json:",omitempty"` // トータル件数
	From  int `json:",omitempty"` // ページング開始ページ
	Count int `json:",omitempty"` // 件数

	Zones []*naked.Zone `json:",omitempty"`
}

// zoneReadResponseEnvelope is envelop of API response
type zoneReadResponseEnvelope struct {
	IsOk    bool            `json:"is_ok,omitempty"` // is_ok項目
	Success types.APIResult `json:",omitempty"`      // success項目

	Zone *naked.Zone `json:",omitempty"`
}
