// generated by 'github.com/sacloud/libsacloud/internal/tools/gen-api-models'; DO NOT EDIT

package sacloud

import (
	"time"

	"github.com/sacloud/libsacloud-v2/pkg/mapconv"
	"github.com/sacloud/libsacloud-v2/sacloud/naked"
	"github.com/sacloud/libsacloud-v2/sacloud/types"
	"gopkg.in/go-playground/validator.v9"
)

/*************************************************
* CDROM
*************************************************/

// CDROM represents API parameter/response structure
type CDROM struct {
	ID           types.ID
	Name         string `validate:"required"`
	Description  string
	DisplayOrder int
	Tags         []string
	Availability types.EAvailability
	Scope        types.EScope
	StorageClass string
	Storage      *naked.Storage `json:",omitempty"`
	Icon         *naked.Icon    `json:",omitempty"`
	CreatedAt    *time.Time
	ModifiedAt   *time.Time
}

// Validate validates by field tags
func (o *CDROM) Validate() error {
	return validator.New().Struct(o)
}

// GetID returns value of ID
func (o *CDROM) GetID() types.ID {
	return o.ID
}

// SetID sets value to ID
func (o *CDROM) SetID(v types.ID) {
	o.ID = v
}

// GetStringID gets value to StringID
func (o *CDROM) GetStringID() string {
	return getStringID(o)
}

// SetStringID sets value to StringID
func (o *CDROM) SetStringID(v string) {
	setStringID(o, v)
}

// GetInt64ID gets value to Int64ID
func (o *CDROM) GetInt64ID() int64 {
	return getInt64ID(o)
}

// SetInt64ID sets value to Int64ID
func (o *CDROM) SetInt64ID(v int64) {
	setInt64ID(o, v)
}

// GetName returns value of Name
func (o *CDROM) GetName() string {
	return o.Name
}

// SetName sets value to Name
func (o *CDROM) SetName(v string) {
	o.Name = v
}

// GetDescription returns value of Description
func (o *CDROM) GetDescription() string {
	return o.Description
}

// SetDescription sets value to Description
func (o *CDROM) SetDescription(v string) {
	o.Description = v
}

// GetDisplayOrder returns value of DisplayOrder
func (o *CDROM) GetDisplayOrder() int {
	return o.DisplayOrder
}

// SetDisplayOrder sets value to DisplayOrder
func (o *CDROM) SetDisplayOrder(v int) {
	o.DisplayOrder = v
}

// GetTags returns value of Tags
func (o *CDROM) GetTags() []string {
	return o.Tags
}

// SetTags sets value to Tags
func (o *CDROM) SetTags(v []string) {
	o.Tags = v
}

// GetAvailability returns value of Availability
func (o *CDROM) GetAvailability() types.EAvailability {
	return o.Availability
}

// SetAvailability sets value to Availability
func (o *CDROM) SetAvailability(v types.EAvailability) {
	o.Availability = v
}

// GetScope returns value of Scope
func (o *CDROM) GetScope() types.EScope {
	return o.Scope
}

// SetScope sets value to Scope
func (o *CDROM) SetScope(v types.EScope) {
	o.Scope = v
}

// GetStorageClass returns value of StorageClass
func (o *CDROM) GetStorageClass() string {
	return o.StorageClass
}

// SetStorageClass sets value to StorageClass
func (o *CDROM) SetStorageClass(v string) {
	o.StorageClass = v
}

// GetStorage returns value of Storage
func (o *CDROM) GetStorage() *naked.Storage {
	return o.Storage
}

// SetStorage sets value to Storage
func (o *CDROM) SetStorage(v *naked.Storage) {
	o.Storage = v
}

// GetIcon returns value of Icon
func (o *CDROM) GetIcon() *naked.Icon {
	return o.Icon
}

// SetIcon sets value to Icon
func (o *CDROM) SetIcon(v *naked.Icon) {
	o.Icon = v
}

// GetCreatedAt returns value of CreatedAt
func (o *CDROM) GetCreatedAt() *time.Time {
	return o.CreatedAt
}

// SetCreatedAt sets value to CreatedAt
func (o *CDROM) SetCreatedAt(v *time.Time) {
	o.CreatedAt = v
}

// GetModifiedAt returns value of ModifiedAt
func (o *CDROM) GetModifiedAt() *time.Time {
	return o.ModifiedAt
}

// SetModifiedAt sets value to ModifiedAt
func (o *CDROM) SetModifiedAt(v *time.Time) {
	o.ModifiedAt = v
}

// convertTo returns naked CDROM
func (o *CDROM) convertTo() (*naked.CDROM, error) {
	dest := &naked.CDROM{}
	err := mapconv.ConvertTo(o, dest)
	return dest, err
}

// convertFrom parse values from naked CDROM
func (o *CDROM) convertFrom(naked *naked.CDROM) error {
	return mapconv.ConvertFrom(naked, o)
}

/*************************************************
* FindCondition
*************************************************/

// FindCondition represents API parameter/response structure
type FindCondition struct {
	Count   int
	From    int
	Sort    []string
	Filter  map[string]interface{}
	Include []string
	Exclude []string
}

// Validate validates by field tags
func (o *FindCondition) Validate() error {
	return validator.New().Struct(o)
}

// GetCount returns value of Count
func (o *FindCondition) GetCount() int {
	return o.Count
}

// SetCount sets value to Count
func (o *FindCondition) SetCount(v int) {
	o.Count = v
}

// GetFrom returns value of From
func (o *FindCondition) GetFrom() int {
	return o.From
}

// SetFrom sets value to From
func (o *FindCondition) SetFrom(v int) {
	o.From = v
}

// GetSort returns value of Sort
func (o *FindCondition) GetSort() []string {
	return o.Sort
}

// SetSort sets value to Sort
func (o *FindCondition) SetSort(v []string) {
	o.Sort = v
}

// GetFilter returns value of Filter
func (o *FindCondition) GetFilter() map[string]interface{} {
	return o.Filter
}

// SetFilter sets value to Filter
func (o *FindCondition) SetFilter(v map[string]interface{}) {
	o.Filter = v
}

// GetInclude returns value of Include
func (o *FindCondition) GetInclude() []string {
	return o.Include
}

// SetInclude sets value to Include
func (o *FindCondition) SetInclude(v []string) {
	o.Include = v
}

// GetExclude returns value of Exclude
func (o *FindCondition) GetExclude() []string {
	return o.Exclude
}

// SetExclude sets value to Exclude
func (o *FindCondition) SetExclude(v []string) {
	o.Exclude = v
}

/*************************************************
* FTPServer
*************************************************/

// FTPServer represents API parameter/response structure
type FTPServer struct {
	HostName  string
	IPAddress string
	User      string
	Password  string
}

// Validate validates by field tags
func (o *FTPServer) Validate() error {
	return validator.New().Struct(o)
}

// GetHostName returns value of HostName
func (o *FTPServer) GetHostName() string {
	return o.HostName
}

// SetHostName sets value to HostName
func (o *FTPServer) SetHostName(v string) {
	o.HostName = v
}

// GetIPAddress returns value of IPAddress
func (o *FTPServer) GetIPAddress() string {
	return o.IPAddress
}

// SetIPAddress sets value to IPAddress
func (o *FTPServer) SetIPAddress(v string) {
	o.IPAddress = v
}

// GetUser returns value of User
func (o *FTPServer) GetUser() string {
	return o.User
}

// SetUser sets value to User
func (o *FTPServer) SetUser(v string) {
	o.User = v
}

// GetPassword returns value of Password
func (o *FTPServer) GetPassword() string {
	return o.Password
}

// SetPassword sets value to Password
func (o *FTPServer) SetPassword(v string) {
	o.Password = v
}

// convertTo returns naked FTPServer
func (o *FTPServer) convertTo() (*naked.OpeningFTPServer, error) {
	dest := &naked.OpeningFTPServer{}
	err := mapconv.ConvertTo(o, dest)
	return dest, err
}

// convertFrom parse values from naked FTPServer
func (o *FTPServer) convertFrom(naked *naked.OpeningFTPServer) error {
	return mapconv.ConvertFrom(naked, o)
}

/*************************************************
* CDROMCreateRequest
*************************************************/

// CDROMCreateRequest represents API parameter/response structure
type CDROMCreateRequest struct {
	SizeMB      int
	Name        string `validate:"required"`
	Description string
	Tags        []string
	IconID      types.ID `mapconv:"Icon.ID"`
}

// Validate validates by field tags
func (o *CDROMCreateRequest) Validate() error {
	return validator.New().Struct(o)
}

// GetSizeMB returns value of SizeMB
func (o *CDROMCreateRequest) GetSizeMB() int {
	return o.SizeMB
}

// SetSizeMB sets value to SizeMB
func (o *CDROMCreateRequest) SetSizeMB(v int) {
	o.SizeMB = v
}

// GetSizeGB gets value to SizeGB
func (o *CDROMCreateRequest) GetSizeGB() int {
	return getSizeGB(o)
}

// SetSizeGB sets value to SizeGB
func (o *CDROMCreateRequest) SetSizeGB(v int) {
	setSizeGB(o, v)
}

// GetName returns value of Name
func (o *CDROMCreateRequest) GetName() string {
	return o.Name
}

// SetName sets value to Name
func (o *CDROMCreateRequest) SetName(v string) {
	o.Name = v
}

// GetDescription returns value of Description
func (o *CDROMCreateRequest) GetDescription() string {
	return o.Description
}

// SetDescription sets value to Description
func (o *CDROMCreateRequest) SetDescription(v string) {
	o.Description = v
}

// GetTags returns value of Tags
func (o *CDROMCreateRequest) GetTags() []string {
	return o.Tags
}

// SetTags sets value to Tags
func (o *CDROMCreateRequest) SetTags(v []string) {
	o.Tags = v
}

// GetIconID returns value of IconID
func (o *CDROMCreateRequest) GetIconID() types.ID {
	return o.IconID
}

// SetIconID sets value to IconID
func (o *CDROMCreateRequest) SetIconID(v types.ID) {
	o.IconID = v
}

// convertTo returns naked CDROMCreateRequest
func (o *CDROMCreateRequest) convertTo() (*naked.CDROM, error) {
	dest := &naked.CDROM{}
	err := mapconv.ConvertTo(o, dest)
	return dest, err
}

// convertFrom parse values from naked CDROMCreateRequest
func (o *CDROMCreateRequest) convertFrom(naked *naked.CDROM) error {
	return mapconv.ConvertFrom(naked, o)
}

/*************************************************
* CDROMUpdateRequest
*************************************************/

// CDROMUpdateRequest represents API parameter/response structure
type CDROMUpdateRequest struct {
	Name        string `validate:"required"`
	Description string
	Tags        []string
	IconID      types.ID `mapconv:"Icon.ID"`
}

// Validate validates by field tags
func (o *CDROMUpdateRequest) Validate() error {
	return validator.New().Struct(o)
}

// GetName returns value of Name
func (o *CDROMUpdateRequest) GetName() string {
	return o.Name
}

// SetName sets value to Name
func (o *CDROMUpdateRequest) SetName(v string) {
	o.Name = v
}

// GetDescription returns value of Description
func (o *CDROMUpdateRequest) GetDescription() string {
	return o.Description
}

// SetDescription sets value to Description
func (o *CDROMUpdateRequest) SetDescription(v string) {
	o.Description = v
}

// GetTags returns value of Tags
func (o *CDROMUpdateRequest) GetTags() []string {
	return o.Tags
}

// SetTags sets value to Tags
func (o *CDROMUpdateRequest) SetTags(v []string) {
	o.Tags = v
}

// GetIconID returns value of IconID
func (o *CDROMUpdateRequest) GetIconID() types.ID {
	return o.IconID
}

// SetIconID sets value to IconID
func (o *CDROMUpdateRequest) SetIconID(v types.ID) {
	o.IconID = v
}

// convertTo returns naked CDROMUpdateRequest
func (o *CDROMUpdateRequest) convertTo() (*naked.CDROM, error) {
	dest := &naked.CDROM{}
	err := mapconv.ConvertTo(o, dest)
	return dest, err
}

// convertFrom parse values from naked CDROMUpdateRequest
func (o *CDROMUpdateRequest) convertFrom(naked *naked.CDROM) error {
	return mapconv.ConvertFrom(naked, o)
}

/*************************************************
* OpenFTPParam
*************************************************/

// OpenFTPParam represents API parameter/response structure
type OpenFTPParam struct {
	ChangePassword bool
}

// Validate validates by field tags
func (o *OpenFTPParam) Validate() error {
	return validator.New().Struct(o)
}

// GetChangePassword returns value of ChangePassword
func (o *OpenFTPParam) GetChangePassword() bool {
	return o.ChangePassword
}

// SetChangePassword sets value to ChangePassword
func (o *OpenFTPParam) SetChangePassword(v bool) {
	o.ChangePassword = v
}

/*************************************************
* GSLB
*************************************************/

// GSLB represents API parameter/response structure
type GSLB struct {
	ID                      types.ID
	Name                    string `validate:"required"`
	Description             string
	Tags                    []string
	Availability            types.EAvailability
	Icon                    *naked.Icon `json:",omitempty"`
	CreatedAt               *time.Time
	ModifiedAt              *time.Time
	Class                   string `mapconv:"Provider.Class,default=gslb"`
	SettingsHash            string
	FQDN                    string             `mapconv:"Status.FQDN"`
	DelayLoop               int                `mapconv:"Settings.GSLB.DelayLoop,default=10" validate:"min=10,max=60"`
	Weighted                types.StringFlag   `mapconv:"Settings.GSLB.Weighted"`
	HealthCheckProtocol     string             `mapconv:"Settings.GSLB.HealthCheck.Protocol" validate:"oneof=http https ping tcp"`
	HealthCheckHostHeader   string             `mapconv:"Settings.GSLB.HealthCheck.Host"`
	HealthCheckPath         string             `mapconv:"Settings.GSLB.HealthCheck.Path"`
	HealthCheckResponseCode types.StringNumber `mapconv:"Settings.GSLB.HealthCheck.Status"`
	HealthCheckPort         types.StringNumber `mapconv:"Settings.GSLB.HealthCheck.Port"`
	SorryServer             string             `mapconv:"Settings.GSLB.SorryServer"`
	DestinationServers      []*GSLBServer      `mapconv:"Settings.GSLB.[]Servers,recursive" validate:"min=0,max=6"`
}

// Validate validates by field tags
func (o *GSLB) Validate() error {
	return validator.New().Struct(o)
}

// GetID returns value of ID
func (o *GSLB) GetID() types.ID {
	return o.ID
}

// SetID sets value to ID
func (o *GSLB) SetID(v types.ID) {
	o.ID = v
}

// GetStringID gets value to StringID
func (o *GSLB) GetStringID() string {
	return getStringID(o)
}

// SetStringID sets value to StringID
func (o *GSLB) SetStringID(v string) {
	setStringID(o, v)
}

// GetInt64ID gets value to Int64ID
func (o *GSLB) GetInt64ID() int64 {
	return getInt64ID(o)
}

// SetInt64ID sets value to Int64ID
func (o *GSLB) SetInt64ID(v int64) {
	setInt64ID(o, v)
}

// GetName returns value of Name
func (o *GSLB) GetName() string {
	return o.Name
}

// SetName sets value to Name
func (o *GSLB) SetName(v string) {
	o.Name = v
}

// GetDescription returns value of Description
func (o *GSLB) GetDescription() string {
	return o.Description
}

// SetDescription sets value to Description
func (o *GSLB) SetDescription(v string) {
	o.Description = v
}

// GetTags returns value of Tags
func (o *GSLB) GetTags() []string {
	return o.Tags
}

// SetTags sets value to Tags
func (o *GSLB) SetTags(v []string) {
	o.Tags = v
}

// GetAvailability returns value of Availability
func (o *GSLB) GetAvailability() types.EAvailability {
	return o.Availability
}

// SetAvailability sets value to Availability
func (o *GSLB) SetAvailability(v types.EAvailability) {
	o.Availability = v
}

// GetIcon returns value of Icon
func (o *GSLB) GetIcon() *naked.Icon {
	return o.Icon
}

// SetIcon sets value to Icon
func (o *GSLB) SetIcon(v *naked.Icon) {
	o.Icon = v
}

// GetCreatedAt returns value of CreatedAt
func (o *GSLB) GetCreatedAt() *time.Time {
	return o.CreatedAt
}

// SetCreatedAt sets value to CreatedAt
func (o *GSLB) SetCreatedAt(v *time.Time) {
	o.CreatedAt = v
}

// GetModifiedAt returns value of ModifiedAt
func (o *GSLB) GetModifiedAt() *time.Time {
	return o.ModifiedAt
}

// SetModifiedAt sets value to ModifiedAt
func (o *GSLB) SetModifiedAt(v *time.Time) {
	o.ModifiedAt = v
}

// GetClass returns value of Class
func (o *GSLB) GetClass() string {
	return o.Class
}

// GetSettingsHash returns value of SettingsHash
func (o *GSLB) GetSettingsHash() string {
	return o.SettingsHash
}

// GetFQDN returns value of FQDN
func (o *GSLB) GetFQDN() string {
	return o.FQDN
}

// GetDelayLoop returns value of DelayLoop
func (o *GSLB) GetDelayLoop() int {
	return o.DelayLoop
}

// SetDelayLoop sets value to DelayLoop
func (o *GSLB) SetDelayLoop(v int) {
	o.DelayLoop = v
}

// GetWeighted returns value of Weighted
func (o *GSLB) GetWeighted() types.StringFlag {
	return o.Weighted
}

// SetWeighted sets value to Weighted
func (o *GSLB) SetWeighted(v types.StringFlag) {
	o.Weighted = v
}

// GetHealthCheckProtocol returns value of HealthCheckProtocol
func (o *GSLB) GetHealthCheckProtocol() string {
	return o.HealthCheckProtocol
}

// SetHealthCheckProtocol sets value to HealthCheckProtocol
func (o *GSLB) SetHealthCheckProtocol(v string) {
	o.HealthCheckProtocol = v
}

// GetHealthCheckHostHeader returns value of HealthCheckHostHeader
func (o *GSLB) GetHealthCheckHostHeader() string {
	return o.HealthCheckHostHeader
}

// SetHealthCheckHostHeader sets value to HealthCheckHostHeader
func (o *GSLB) SetHealthCheckHostHeader(v string) {
	o.HealthCheckHostHeader = v
}

// GetHealthCheckPath returns value of HealthCheckPath
func (o *GSLB) GetHealthCheckPath() string {
	return o.HealthCheckPath
}

// SetHealthCheckPath sets value to HealthCheckPath
func (o *GSLB) SetHealthCheckPath(v string) {
	o.HealthCheckPath = v
}

// GetHealthCheckResponseCode returns value of HealthCheckResponseCode
func (o *GSLB) GetHealthCheckResponseCode() types.StringNumber {
	return o.HealthCheckResponseCode
}

// SetHealthCheckResponseCode sets value to HealthCheckResponseCode
func (o *GSLB) SetHealthCheckResponseCode(v types.StringNumber) {
	o.HealthCheckResponseCode = v
}

// GetHealthCheckPort returns value of HealthCheckPort
func (o *GSLB) GetHealthCheckPort() types.StringNumber {
	return o.HealthCheckPort
}

// SetHealthCheckPort sets value to HealthCheckPort
func (o *GSLB) SetHealthCheckPort(v types.StringNumber) {
	o.HealthCheckPort = v
}

// GetSorryServer returns value of SorryServer
func (o *GSLB) GetSorryServer() string {
	return o.SorryServer
}

// SetSorryServer sets value to SorryServer
func (o *GSLB) SetSorryServer(v string) {
	o.SorryServer = v
}

// GetDestinationServers returns value of DestinationServers
func (o *GSLB) GetDestinationServers() []*GSLBServer {
	return o.DestinationServers
}

// SetDestinationServers sets value to DestinationServers
func (o *GSLB) SetDestinationServers(v []*GSLBServer) {
	o.DestinationServers = v
}

// convertTo returns naked GSLB
func (o *GSLB) convertTo() (*naked.GSLB, error) {
	dest := &naked.GSLB{}
	err := mapconv.ConvertTo(o, dest)
	return dest, err
}

// convertFrom parse values from naked GSLB
func (o *GSLB) convertFrom(naked *naked.GSLB) error {
	return mapconv.ConvertFrom(naked, o)
}

/*************************************************
* GSLBCreateRequest
*************************************************/

// GSLBCreateRequest represents API parameter/response structure
type GSLBCreateRequest struct {
	Class                   string             `mapconv:"Provider.Class,default=gslb"`
	HealthCheckProtocol     string             `mapconv:"Settings.GSLB.HealthCheck.Protocol" validate:"oneof=http https ping tcp"`
	HealthCheckHostHeader   string             `mapconv:"Settings.GSLB.HealthCheck.Host"`
	HealthCheckPath         string             `mapconv:"Settings.GSLB.HealthCheck.Path"`
	HealthCheckResponseCode types.StringNumber `mapconv:"Settings.GSLB.HealthCheck.Status"`
	HealthCheckPort         types.StringNumber `mapconv:"Settings.GSLB.HealthCheck.Port"`
	DelayLoop               int                `mapconv:"Settings.GSLB.DelayLoop,default=10" validate:"min=10,max=60"`
	Weighted                types.StringFlag   `mapconv:"Settings.GSLB.Weighted"`
	SorryServer             string             `mapconv:"Settings.GSLB.SorryServer"`
	DestinationServers      []*GSLBServer      `mapconv:"Settings.GSLB.[]Servers,recursive" validate:"min=0,max=6"`
	Name                    string             `validate:"required"`
	Description             string
	Tags                    []string
	IconID                  types.ID `mapconv:"Icon.ID"`
}

// Validate validates by field tags
func (o *GSLBCreateRequest) Validate() error {
	return validator.New().Struct(o)
}

// GetClass returns value of Class
func (o *GSLBCreateRequest) GetClass() string {
	return o.Class
}

// GetHealthCheckProtocol returns value of HealthCheckProtocol
func (o *GSLBCreateRequest) GetHealthCheckProtocol() string {
	return o.HealthCheckProtocol
}

// SetHealthCheckProtocol sets value to HealthCheckProtocol
func (o *GSLBCreateRequest) SetHealthCheckProtocol(v string) {
	o.HealthCheckProtocol = v
}

// GetHealthCheckHostHeader returns value of HealthCheckHostHeader
func (o *GSLBCreateRequest) GetHealthCheckHostHeader() string {
	return o.HealthCheckHostHeader
}

// SetHealthCheckHostHeader sets value to HealthCheckHostHeader
func (o *GSLBCreateRequest) SetHealthCheckHostHeader(v string) {
	o.HealthCheckHostHeader = v
}

// GetHealthCheckPath returns value of HealthCheckPath
func (o *GSLBCreateRequest) GetHealthCheckPath() string {
	return o.HealthCheckPath
}

// SetHealthCheckPath sets value to HealthCheckPath
func (o *GSLBCreateRequest) SetHealthCheckPath(v string) {
	o.HealthCheckPath = v
}

// GetHealthCheckResponseCode returns value of HealthCheckResponseCode
func (o *GSLBCreateRequest) GetHealthCheckResponseCode() types.StringNumber {
	return o.HealthCheckResponseCode
}

// SetHealthCheckResponseCode sets value to HealthCheckResponseCode
func (o *GSLBCreateRequest) SetHealthCheckResponseCode(v types.StringNumber) {
	o.HealthCheckResponseCode = v
}

// GetHealthCheckPort returns value of HealthCheckPort
func (o *GSLBCreateRequest) GetHealthCheckPort() types.StringNumber {
	return o.HealthCheckPort
}

// SetHealthCheckPort sets value to HealthCheckPort
func (o *GSLBCreateRequest) SetHealthCheckPort(v types.StringNumber) {
	o.HealthCheckPort = v
}

// GetDelayLoop returns value of DelayLoop
func (o *GSLBCreateRequest) GetDelayLoop() int {
	return o.DelayLoop
}

// SetDelayLoop sets value to DelayLoop
func (o *GSLBCreateRequest) SetDelayLoop(v int) {
	o.DelayLoop = v
}

// GetWeighted returns value of Weighted
func (o *GSLBCreateRequest) GetWeighted() types.StringFlag {
	return o.Weighted
}

// SetWeighted sets value to Weighted
func (o *GSLBCreateRequest) SetWeighted(v types.StringFlag) {
	o.Weighted = v
}

// GetSorryServer returns value of SorryServer
func (o *GSLBCreateRequest) GetSorryServer() string {
	return o.SorryServer
}

// SetSorryServer sets value to SorryServer
func (o *GSLBCreateRequest) SetSorryServer(v string) {
	o.SorryServer = v
}

// GetDestinationServers returns value of DestinationServers
func (o *GSLBCreateRequest) GetDestinationServers() []*GSLBServer {
	return o.DestinationServers
}

// SetDestinationServers sets value to DestinationServers
func (o *GSLBCreateRequest) SetDestinationServers(v []*GSLBServer) {
	o.DestinationServers = v
}

// GetName returns value of Name
func (o *GSLBCreateRequest) GetName() string {
	return o.Name
}

// SetName sets value to Name
func (o *GSLBCreateRequest) SetName(v string) {
	o.Name = v
}

// GetDescription returns value of Description
func (o *GSLBCreateRequest) GetDescription() string {
	return o.Description
}

// SetDescription sets value to Description
func (o *GSLBCreateRequest) SetDescription(v string) {
	o.Description = v
}

// GetTags returns value of Tags
func (o *GSLBCreateRequest) GetTags() []string {
	return o.Tags
}

// SetTags sets value to Tags
func (o *GSLBCreateRequest) SetTags(v []string) {
	o.Tags = v
}

// GetIconID returns value of IconID
func (o *GSLBCreateRequest) GetIconID() types.ID {
	return o.IconID
}

// SetIconID sets value to IconID
func (o *GSLBCreateRequest) SetIconID(v types.ID) {
	o.IconID = v
}

// convertTo returns naked GSLBCreateRequest
func (o *GSLBCreateRequest) convertTo() (*naked.GSLB, error) {
	dest := &naked.GSLB{}
	err := mapconv.ConvertTo(o, dest)
	return dest, err
}

// convertFrom parse values from naked GSLBCreateRequest
func (o *GSLBCreateRequest) convertFrom(naked *naked.GSLB) error {
	return mapconv.ConvertFrom(naked, o)
}

/*************************************************
* GSLBServer
*************************************************/

// GSLBServer represents API parameter/response structure
type GSLBServer struct {
	IPAddress string             `validate:"ipv4"`
	Enabled   types.StringFlag   `mapconv:",default=true"`
	Weight    types.StringNumber `mapconv:",default=1"`
}

// Validate validates by field tags
func (o *GSLBServer) Validate() error {
	return validator.New().Struct(o)
}

// GetIPAddress returns value of IPAddress
func (o *GSLBServer) GetIPAddress() string {
	return o.IPAddress
}

// SetIPAddress sets value to IPAddress
func (o *GSLBServer) SetIPAddress(v string) {
	o.IPAddress = v
}

// GetEnabled returns value of Enabled
func (o *GSLBServer) GetEnabled() types.StringFlag {
	return o.Enabled
}

// SetEnabled sets value to Enabled
func (o *GSLBServer) SetEnabled(v types.StringFlag) {
	o.Enabled = v
}

// GetWeight returns value of Weight
func (o *GSLBServer) GetWeight() types.StringNumber {
	return o.Weight
}

// SetWeight sets value to Weight
func (o *GSLBServer) SetWeight(v types.StringNumber) {
	o.Weight = v
}

/*************************************************
* GSLBUpdateRequest
*************************************************/

// GSLBUpdateRequest represents API parameter/response structure
type GSLBUpdateRequest struct {
	HealthCheckProtocol     string             `mapconv:"Settings.GSLB.HealthCheck.Protocol" validate:"oneof=http https ping tcp"`
	HealthCheckHostHeader   string             `mapconv:"Settings.GSLB.HealthCheck.Host"`
	HealthCheckPath         string             `mapconv:"Settings.GSLB.HealthCheck.Path"`
	HealthCheckResponseCode types.StringNumber `mapconv:"Settings.GSLB.HealthCheck.Status"`
	HealthCheckPort         types.StringNumber `mapconv:"Settings.GSLB.HealthCheck.Port"`
	DelayLoop               int                `mapconv:"Settings.GSLB.DelayLoop,default=10" validate:"min=10,max=60"`
	Weighted                types.StringFlag   `mapconv:"Settings.GSLB.Weighted"`
	SorryServer             string             `mapconv:"Settings.GSLB.SorryServer"`
	DestinationServers      []*GSLBServer      `mapconv:"Settings.GSLB.[]Servers,recursive" validate:"min=0,max=6"`
	Name                    string             `validate:"required"`
	Description             string
	Tags                    []string
	IconID                  types.ID `mapconv:"Icon.ID"`
}

// Validate validates by field tags
func (o *GSLBUpdateRequest) Validate() error {
	return validator.New().Struct(o)
}

// GetHealthCheckProtocol returns value of HealthCheckProtocol
func (o *GSLBUpdateRequest) GetHealthCheckProtocol() string {
	return o.HealthCheckProtocol
}

// SetHealthCheckProtocol sets value to HealthCheckProtocol
func (o *GSLBUpdateRequest) SetHealthCheckProtocol(v string) {
	o.HealthCheckProtocol = v
}

// GetHealthCheckHostHeader returns value of HealthCheckHostHeader
func (o *GSLBUpdateRequest) GetHealthCheckHostHeader() string {
	return o.HealthCheckHostHeader
}

// SetHealthCheckHostHeader sets value to HealthCheckHostHeader
func (o *GSLBUpdateRequest) SetHealthCheckHostHeader(v string) {
	o.HealthCheckHostHeader = v
}

// GetHealthCheckPath returns value of HealthCheckPath
func (o *GSLBUpdateRequest) GetHealthCheckPath() string {
	return o.HealthCheckPath
}

// SetHealthCheckPath sets value to HealthCheckPath
func (o *GSLBUpdateRequest) SetHealthCheckPath(v string) {
	o.HealthCheckPath = v
}

// GetHealthCheckResponseCode returns value of HealthCheckResponseCode
func (o *GSLBUpdateRequest) GetHealthCheckResponseCode() types.StringNumber {
	return o.HealthCheckResponseCode
}

// SetHealthCheckResponseCode sets value to HealthCheckResponseCode
func (o *GSLBUpdateRequest) SetHealthCheckResponseCode(v types.StringNumber) {
	o.HealthCheckResponseCode = v
}

// GetHealthCheckPort returns value of HealthCheckPort
func (o *GSLBUpdateRequest) GetHealthCheckPort() types.StringNumber {
	return o.HealthCheckPort
}

// SetHealthCheckPort sets value to HealthCheckPort
func (o *GSLBUpdateRequest) SetHealthCheckPort(v types.StringNumber) {
	o.HealthCheckPort = v
}

// GetDelayLoop returns value of DelayLoop
func (o *GSLBUpdateRequest) GetDelayLoop() int {
	return o.DelayLoop
}

// SetDelayLoop sets value to DelayLoop
func (o *GSLBUpdateRequest) SetDelayLoop(v int) {
	o.DelayLoop = v
}

// GetWeighted returns value of Weighted
func (o *GSLBUpdateRequest) GetWeighted() types.StringFlag {
	return o.Weighted
}

// SetWeighted sets value to Weighted
func (o *GSLBUpdateRequest) SetWeighted(v types.StringFlag) {
	o.Weighted = v
}

// GetSorryServer returns value of SorryServer
func (o *GSLBUpdateRequest) GetSorryServer() string {
	return o.SorryServer
}

// SetSorryServer sets value to SorryServer
func (o *GSLBUpdateRequest) SetSorryServer(v string) {
	o.SorryServer = v
}

// GetDestinationServers returns value of DestinationServers
func (o *GSLBUpdateRequest) GetDestinationServers() []*GSLBServer {
	return o.DestinationServers
}

// SetDestinationServers sets value to DestinationServers
func (o *GSLBUpdateRequest) SetDestinationServers(v []*GSLBServer) {
	o.DestinationServers = v
}

// GetName returns value of Name
func (o *GSLBUpdateRequest) GetName() string {
	return o.Name
}

// SetName sets value to Name
func (o *GSLBUpdateRequest) SetName(v string) {
	o.Name = v
}

// GetDescription returns value of Description
func (o *GSLBUpdateRequest) GetDescription() string {
	return o.Description
}

// SetDescription sets value to Description
func (o *GSLBUpdateRequest) SetDescription(v string) {
	o.Description = v
}

// GetTags returns value of Tags
func (o *GSLBUpdateRequest) GetTags() []string {
	return o.Tags
}

// SetTags sets value to Tags
func (o *GSLBUpdateRequest) SetTags(v []string) {
	o.Tags = v
}

// GetIconID returns value of IconID
func (o *GSLBUpdateRequest) GetIconID() types.ID {
	return o.IconID
}

// SetIconID sets value to IconID
func (o *GSLBUpdateRequest) SetIconID(v types.ID) {
	o.IconID = v
}

// convertTo returns naked GSLBUpdateRequest
func (o *GSLBUpdateRequest) convertTo() (*naked.GSLB, error) {
	dest := &naked.GSLB{}
	err := mapconv.ConvertTo(o, dest)
	return dest, err
}

// convertFrom parse values from naked GSLBUpdateRequest
func (o *GSLBUpdateRequest) convertFrom(naked *naked.GSLB) error {
	return mapconv.ConvertFrom(naked, o)
}

/*************************************************
* NFS
*************************************************/

// NFS represents API parameter/response structure
type NFS struct {
	ID                      types.ID
	Name                    string `validate:"required"`
	Description             string
	Tags                    []string
	Availability            types.EAvailability
	Class                   string
	InstanceHostName        string                      `mapconv:"Instance.Host.Name"`
	InstanceHostInfoURL     string                      `mapconv:"Instance.Host.InfoURL"`
	InstanceStatus          types.EServerInstanceStatus `mapconv:"Instance.Status"`
	InstanceStatusChangedAt *time.Time                  `mapconv:"Instance.StatusChangedAt"`
	Interfaces              []naked.Interface
	PlanID                  types.ID      `mapconv:"Remark.Plan.ID,Plan.ID"`
	SwitchID                types.ID      `mapconv:"Remark.Switch.ID"`
	Switch                  *naked.Switch `json:",omitempty"`
	DefaultRoute            string        `mapconv:"Remark.Network.DefaultRoute" validate:"ipv4"`
	NetworkMaskLen          int           `mapconv:"Remark.Network.NetworkMaskLen" validate:"min=1,max=32"`
	IPAddresses             []string      `mapconv:"Remark.[]Servers.IPAddress"`
	ZoneID                  types.ID      `mapconv:"Remark.Zone.ID"`
	Icon                    *naked.Icon   `json:",omitempty"`
	CreatedAt               *time.Time
	ModifiedAt              *time.Time
}

// Validate validates by field tags
func (o *NFS) Validate() error {
	return validator.New().Struct(o)
}

// GetID returns value of ID
func (o *NFS) GetID() types.ID {
	return o.ID
}

// SetID sets value to ID
func (o *NFS) SetID(v types.ID) {
	o.ID = v
}

// GetStringID gets value to StringID
func (o *NFS) GetStringID() string {
	return getStringID(o)
}

// SetStringID sets value to StringID
func (o *NFS) SetStringID(v string) {
	setStringID(o, v)
}

// GetInt64ID gets value to Int64ID
func (o *NFS) GetInt64ID() int64 {
	return getInt64ID(o)
}

// SetInt64ID sets value to Int64ID
func (o *NFS) SetInt64ID(v int64) {
	setInt64ID(o, v)
}

// GetName returns value of Name
func (o *NFS) GetName() string {
	return o.Name
}

// SetName sets value to Name
func (o *NFS) SetName(v string) {
	o.Name = v
}

// GetDescription returns value of Description
func (o *NFS) GetDescription() string {
	return o.Description
}

// SetDescription sets value to Description
func (o *NFS) SetDescription(v string) {
	o.Description = v
}

// GetTags returns value of Tags
func (o *NFS) GetTags() []string {
	return o.Tags
}

// SetTags sets value to Tags
func (o *NFS) SetTags(v []string) {
	o.Tags = v
}

// GetAvailability returns value of Availability
func (o *NFS) GetAvailability() types.EAvailability {
	return o.Availability
}

// SetAvailability sets value to Availability
func (o *NFS) SetAvailability(v types.EAvailability) {
	o.Availability = v
}

// GetClass returns value of Class
func (o *NFS) GetClass() string {
	return o.Class
}

// SetClass sets value to Class
func (o *NFS) SetClass(v string) {
	o.Class = v
}

// GetInstanceHostName returns value of InstanceHostName
func (o *NFS) GetInstanceHostName() string {
	return o.InstanceHostName
}

// GetInstanceHostInfoURL returns value of InstanceHostInfoURL
func (o *NFS) GetInstanceHostInfoURL() string {
	return o.InstanceHostInfoURL
}

// GetInstanceStatus returns value of InstanceStatus
func (o *NFS) GetInstanceStatus() types.EServerInstanceStatus {
	return o.InstanceStatus
}

// GetInstanceStatusChangedAt returns value of InstanceStatusChangedAt
func (o *NFS) GetInstanceStatusChangedAt() *time.Time {
	return o.InstanceStatusChangedAt
}

// GetInterfaces returns value of Interfaces
func (o *NFS) GetInterfaces() []naked.Interface {
	return o.Interfaces
}

// GetPlanID returns value of PlanID
func (o *NFS) GetPlanID() types.ID {
	return o.PlanID
}

// SetPlanID sets value to PlanID
func (o *NFS) SetPlanID(v types.ID) {
	o.PlanID = v
}

// GetSwitchID returns value of SwitchID
func (o *NFS) GetSwitchID() types.ID {
	return o.SwitchID
}

// SetSwitchID sets value to SwitchID
func (o *NFS) SetSwitchID(v types.ID) {
	o.SwitchID = v
}

// GetSwitch returns value of Switch
func (o *NFS) GetSwitch() *naked.Switch {
	return o.Switch
}

// SetSwitch sets value to Switch
func (o *NFS) SetSwitch(v *naked.Switch) {
	o.Switch = v
}

// GetDefaultRoute returns value of DefaultRoute
func (o *NFS) GetDefaultRoute() string {
	return o.DefaultRoute
}

// SetDefaultRoute sets value to DefaultRoute
func (o *NFS) SetDefaultRoute(v string) {
	o.DefaultRoute = v
}

// GetNetworkMaskLen returns value of NetworkMaskLen
func (o *NFS) GetNetworkMaskLen() int {
	return o.NetworkMaskLen
}

// SetNetworkMaskLen sets value to NetworkMaskLen
func (o *NFS) SetNetworkMaskLen(v int) {
	o.NetworkMaskLen = v
}

// GetIPAddresses returns value of IPAddresses
func (o *NFS) GetIPAddresses() []string {
	return o.IPAddresses
}

// SetIPAddresses sets value to IPAddresses
func (o *NFS) SetIPAddresses(v []string) {
	o.IPAddresses = v
}

// GetZoneID returns value of ZoneID
func (o *NFS) GetZoneID() types.ID {
	return o.ZoneID
}

// GetIcon returns value of Icon
func (o *NFS) GetIcon() *naked.Icon {
	return o.Icon
}

// SetIcon sets value to Icon
func (o *NFS) SetIcon(v *naked.Icon) {
	o.Icon = v
}

// GetCreatedAt returns value of CreatedAt
func (o *NFS) GetCreatedAt() *time.Time {
	return o.CreatedAt
}

// SetCreatedAt sets value to CreatedAt
func (o *NFS) SetCreatedAt(v *time.Time) {
	o.CreatedAt = v
}

// GetModifiedAt returns value of ModifiedAt
func (o *NFS) GetModifiedAt() *time.Time {
	return o.ModifiedAt
}

// SetModifiedAt sets value to ModifiedAt
func (o *NFS) SetModifiedAt(v *time.Time) {
	o.ModifiedAt = v
}

// convertTo returns naked NFS
func (o *NFS) convertTo() (*naked.NFS, error) {
	dest := &naked.NFS{}
	err := mapconv.ConvertTo(o, dest)
	return dest, err
}

// convertFrom parse values from naked NFS
func (o *NFS) convertFrom(naked *naked.NFS) error {
	return mapconv.ConvertFrom(naked, o)
}

/*************************************************
* NFSCreateRequest
*************************************************/

// NFSCreateRequest represents API parameter/response structure
type NFSCreateRequest struct {
	Class          string   `mapconv:",default=nfs"`
	SwitchID       types.ID `mapconv:"Remark.Switch.ID"`
	PlanID         types.ID `mapconv:"Remark.Plan.ID,Plan.ID"`
	IPAddress      string   `mapconv:"Remark.[]Servers.IPAddress"`
	NetworkMaskLen int      `mapconv:"Remark.Network.NetworkMaskLen" validate:"min=1,max=32"`
	DefaultRoute   string   `mapconv:"Remark.Network.DefaultRoute" validate:"ipv4"`
	Name           string   `validate:"required"`
	Description    string
	Tags           []string
	IconID         types.ID `mapconv:"Icon.ID"`
}

// Validate validates by field tags
func (o *NFSCreateRequest) Validate() error {
	return validator.New().Struct(o)
}

// GetClass returns value of Class
func (o *NFSCreateRequest) GetClass() string {
	return o.Class
}

// GetSwitchID returns value of SwitchID
func (o *NFSCreateRequest) GetSwitchID() types.ID {
	return o.SwitchID
}

// SetSwitchID sets value to SwitchID
func (o *NFSCreateRequest) SetSwitchID(v types.ID) {
	o.SwitchID = v
}

// GetPlanID returns value of PlanID
func (o *NFSCreateRequest) GetPlanID() types.ID {
	return o.PlanID
}

// SetPlanID sets value to PlanID
func (o *NFSCreateRequest) SetPlanID(v types.ID) {
	o.PlanID = v
}

// GetIPAddress returns value of IPAddress
func (o *NFSCreateRequest) GetIPAddress() string {
	return o.IPAddress
}

// SetIPAddress sets value to IPAddress
func (o *NFSCreateRequest) SetIPAddress(v string) {
	o.IPAddress = v
}

// GetNetworkMaskLen returns value of NetworkMaskLen
func (o *NFSCreateRequest) GetNetworkMaskLen() int {
	return o.NetworkMaskLen
}

// SetNetworkMaskLen sets value to NetworkMaskLen
func (o *NFSCreateRequest) SetNetworkMaskLen(v int) {
	o.NetworkMaskLen = v
}

// GetDefaultRoute returns value of DefaultRoute
func (o *NFSCreateRequest) GetDefaultRoute() string {
	return o.DefaultRoute
}

// SetDefaultRoute sets value to DefaultRoute
func (o *NFSCreateRequest) SetDefaultRoute(v string) {
	o.DefaultRoute = v
}

// GetName returns value of Name
func (o *NFSCreateRequest) GetName() string {
	return o.Name
}

// SetName sets value to Name
func (o *NFSCreateRequest) SetName(v string) {
	o.Name = v
}

// GetDescription returns value of Description
func (o *NFSCreateRequest) GetDescription() string {
	return o.Description
}

// SetDescription sets value to Description
func (o *NFSCreateRequest) SetDescription(v string) {
	o.Description = v
}

// GetTags returns value of Tags
func (o *NFSCreateRequest) GetTags() []string {
	return o.Tags
}

// SetTags sets value to Tags
func (o *NFSCreateRequest) SetTags(v []string) {
	o.Tags = v
}

// GetIconID returns value of IconID
func (o *NFSCreateRequest) GetIconID() types.ID {
	return o.IconID
}

// SetIconID sets value to IconID
func (o *NFSCreateRequest) SetIconID(v types.ID) {
	o.IconID = v
}

// convertTo returns naked NFSCreateRequest
func (o *NFSCreateRequest) convertTo() (*naked.NFS, error) {
	dest := &naked.NFS{}
	err := mapconv.ConvertTo(o, dest)
	return dest, err
}

// convertFrom parse values from naked NFSCreateRequest
func (o *NFSCreateRequest) convertFrom(naked *naked.NFS) error {
	return mapconv.ConvertFrom(naked, o)
}

/*************************************************
* NFSUpdateRequest
*************************************************/

// NFSUpdateRequest represents API parameter/response structure
type NFSUpdateRequest struct {
	Name        string `validate:"required"`
	Description string
	Tags        []string
	IconID      types.ID `mapconv:"Icon.ID"`
}

// Validate validates by field tags
func (o *NFSUpdateRequest) Validate() error {
	return validator.New().Struct(o)
}

// GetName returns value of Name
func (o *NFSUpdateRequest) GetName() string {
	return o.Name
}

// SetName sets value to Name
func (o *NFSUpdateRequest) SetName(v string) {
	o.Name = v
}

// GetDescription returns value of Description
func (o *NFSUpdateRequest) GetDescription() string {
	return o.Description
}

// SetDescription sets value to Description
func (o *NFSUpdateRequest) SetDescription(v string) {
	o.Description = v
}

// GetTags returns value of Tags
func (o *NFSUpdateRequest) GetTags() []string {
	return o.Tags
}

// SetTags sets value to Tags
func (o *NFSUpdateRequest) SetTags(v []string) {
	o.Tags = v
}

// GetIconID returns value of IconID
func (o *NFSUpdateRequest) GetIconID() types.ID {
	return o.IconID
}

// SetIconID sets value to IconID
func (o *NFSUpdateRequest) SetIconID(v types.ID) {
	o.IconID = v
}

// convertTo returns naked NFSUpdateRequest
func (o *NFSUpdateRequest) convertTo() (*naked.NFS, error) {
	dest := &naked.NFS{}
	err := mapconv.ConvertTo(o, dest)
	return dest, err
}

// convertFrom parse values from naked NFSUpdateRequest
func (o *NFSUpdateRequest) convertFrom(naked *naked.NFS) error {
	return mapconv.ConvertFrom(naked, o)
}

/*************************************************
* ShutdownOption
*************************************************/

// ShutdownOption represents API parameter/response structure
type ShutdownOption struct {
	Force bool
}

// Validate validates by field tags
func (o *ShutdownOption) Validate() error {
	return validator.New().Struct(o)
}

// GetForce returns value of Force
func (o *ShutdownOption) GetForce() bool {
	return o.Force
}

// SetForce sets value to Force
func (o *ShutdownOption) SetForce(v bool) {
	o.Force = v
}

/*************************************************
* FreeDiskSizeActivity
*************************************************/

// FreeDiskSizeActivity represents API parameter/response structure
type FreeDiskSizeActivity struct {
	Values []naked.MonitorFreeDiskSizeValue `mapconv:"FreeDiskSize"`
}

// Validate validates by field tags
func (o *FreeDiskSizeActivity) Validate() error {
	return validator.New().Struct(o)
}

// GetValues returns value of Values
func (o *FreeDiskSizeActivity) GetValues() []naked.MonitorFreeDiskSizeValue {
	return o.Values
}

// convertTo returns naked FreeDiskSizeActivity
func (o *FreeDiskSizeActivity) convertTo() (*naked.MonitorValues, error) {
	dest := &naked.MonitorValues{}
	err := mapconv.ConvertTo(o, dest)
	return dest, err
}

// convertFrom parse values from naked FreeDiskSizeActivity
func (o *FreeDiskSizeActivity) convertFrom(naked *naked.MonitorValues) error {
	return mapconv.ConvertFrom(naked, o)
}

/*************************************************
* MonitorCondition
*************************************************/

// MonitorCondition represents API parameter/response structure
type MonitorCondition struct {
	Start *time.Time `json:",omitempty"`
	End   *time.Time `json:",omitempty"`
}

// Validate validates by field tags
func (o *MonitorCondition) Validate() error {
	return validator.New().Struct(o)
}

// GetStart returns value of Start
func (o *MonitorCondition) GetStart() *time.Time {
	return o.Start
}

// SetStart sets value to Start
func (o *MonitorCondition) SetStart(v *time.Time) {
	o.Start = v
}

// GetEnd returns value of End
func (o *MonitorCondition) GetEnd() *time.Time {
	return o.End
}

// SetEnd sets value to End
func (o *MonitorCondition) SetEnd(v *time.Time) {
	o.End = v
}

/*************************************************
* InterfaceActivity
*************************************************/

// InterfaceActivity represents API parameter/response structure
type InterfaceActivity struct {
	Values []naked.MonitorInterfaceValue `mapconv:"Interface"`
}

// Validate validates by field tags
func (o *InterfaceActivity) Validate() error {
	return validator.New().Struct(o)
}

// GetValues returns value of Values
func (o *InterfaceActivity) GetValues() []naked.MonitorInterfaceValue {
	return o.Values
}

// convertTo returns naked InterfaceActivity
func (o *InterfaceActivity) convertTo() (*naked.MonitorValues, error) {
	dest := &naked.MonitorValues{}
	err := mapconv.ConvertTo(o, dest)
	return dest, err
}

// convertFrom parse values from naked InterfaceActivity
func (o *InterfaceActivity) convertFrom(naked *naked.MonitorValues) error {
	return mapconv.ConvertFrom(naked, o)
}

/*************************************************
* Note
*************************************************/

// Note represents API parameter/response structure
type Note struct {
	ID           types.ID
	Name         string `validate:"required"`
	Description  string
	Tags         []string
	Availability types.EAvailability
	Scope        types.EScope
	Class        string
	Content      string
	Icon         *naked.Icon `json:",omitempty"`
	CreatedAt    *time.Time
	ModifiedAt   *time.Time
}

// Validate validates by field tags
func (o *Note) Validate() error {
	return validator.New().Struct(o)
}

// GetID returns value of ID
func (o *Note) GetID() types.ID {
	return o.ID
}

// SetID sets value to ID
func (o *Note) SetID(v types.ID) {
	o.ID = v
}

// GetStringID gets value to StringID
func (o *Note) GetStringID() string {
	return getStringID(o)
}

// SetStringID sets value to StringID
func (o *Note) SetStringID(v string) {
	setStringID(o, v)
}

// GetInt64ID gets value to Int64ID
func (o *Note) GetInt64ID() int64 {
	return getInt64ID(o)
}

// SetInt64ID sets value to Int64ID
func (o *Note) SetInt64ID(v int64) {
	setInt64ID(o, v)
}

// GetName returns value of Name
func (o *Note) GetName() string {
	return o.Name
}

// SetName sets value to Name
func (o *Note) SetName(v string) {
	o.Name = v
}

// GetDescription returns value of Description
func (o *Note) GetDescription() string {
	return o.Description
}

// SetDescription sets value to Description
func (o *Note) SetDescription(v string) {
	o.Description = v
}

// GetTags returns value of Tags
func (o *Note) GetTags() []string {
	return o.Tags
}

// SetTags sets value to Tags
func (o *Note) SetTags(v []string) {
	o.Tags = v
}

// GetAvailability returns value of Availability
func (o *Note) GetAvailability() types.EAvailability {
	return o.Availability
}

// SetAvailability sets value to Availability
func (o *Note) SetAvailability(v types.EAvailability) {
	o.Availability = v
}

// GetScope returns value of Scope
func (o *Note) GetScope() types.EScope {
	return o.Scope
}

// SetScope sets value to Scope
func (o *Note) SetScope(v types.EScope) {
	o.Scope = v
}

// GetClass returns value of Class
func (o *Note) GetClass() string {
	return o.Class
}

// SetClass sets value to Class
func (o *Note) SetClass(v string) {
	o.Class = v
}

// GetContent returns value of Content
func (o *Note) GetContent() string {
	return o.Content
}

// SetContent sets value to Content
func (o *Note) SetContent(v string) {
	o.Content = v
}

// GetIcon returns value of Icon
func (o *Note) GetIcon() *naked.Icon {
	return o.Icon
}

// SetIcon sets value to Icon
func (o *Note) SetIcon(v *naked.Icon) {
	o.Icon = v
}

// GetCreatedAt returns value of CreatedAt
func (o *Note) GetCreatedAt() *time.Time {
	return o.CreatedAt
}

// SetCreatedAt sets value to CreatedAt
func (o *Note) SetCreatedAt(v *time.Time) {
	o.CreatedAt = v
}

// GetModifiedAt returns value of ModifiedAt
func (o *Note) GetModifiedAt() *time.Time {
	return o.ModifiedAt
}

// SetModifiedAt sets value to ModifiedAt
func (o *Note) SetModifiedAt(v *time.Time) {
	o.ModifiedAt = v
}

// convertTo returns naked Note
func (o *Note) convertTo() (*naked.Note, error) {
	dest := &naked.Note{}
	err := mapconv.ConvertTo(o, dest)
	return dest, err
}

// convertFrom parse values from naked Note
func (o *Note) convertFrom(naked *naked.Note) error {
	return mapconv.ConvertFrom(naked, o)
}

/*************************************************
* NoteCreateRequest
*************************************************/

// NoteCreateRequest represents API parameter/response structure
type NoteCreateRequest struct {
	Name    string `validate:"required"`
	Tags    []string
	IconID  types.ID `mapconv:"Icon.ID"`
	Class   string
	Content string
}

// Validate validates by field tags
func (o *NoteCreateRequest) Validate() error {
	return validator.New().Struct(o)
}

// GetName returns value of Name
func (o *NoteCreateRequest) GetName() string {
	return o.Name
}

// SetName sets value to Name
func (o *NoteCreateRequest) SetName(v string) {
	o.Name = v
}

// GetTags returns value of Tags
func (o *NoteCreateRequest) GetTags() []string {
	return o.Tags
}

// SetTags sets value to Tags
func (o *NoteCreateRequest) SetTags(v []string) {
	o.Tags = v
}

// GetIconID returns value of IconID
func (o *NoteCreateRequest) GetIconID() types.ID {
	return o.IconID
}

// SetIconID sets value to IconID
func (o *NoteCreateRequest) SetIconID(v types.ID) {
	o.IconID = v
}

// GetClass returns value of Class
func (o *NoteCreateRequest) GetClass() string {
	return o.Class
}

// SetClass sets value to Class
func (o *NoteCreateRequest) SetClass(v string) {
	o.Class = v
}

// GetContent returns value of Content
func (o *NoteCreateRequest) GetContent() string {
	return o.Content
}

// SetContent sets value to Content
func (o *NoteCreateRequest) SetContent(v string) {
	o.Content = v
}

// convertTo returns naked NoteCreateRequest
func (o *NoteCreateRequest) convertTo() (*naked.Note, error) {
	dest := &naked.Note{}
	err := mapconv.ConvertTo(o, dest)
	return dest, err
}

// convertFrom parse values from naked NoteCreateRequest
func (o *NoteCreateRequest) convertFrom(naked *naked.Note) error {
	return mapconv.ConvertFrom(naked, o)
}

/*************************************************
* NoteUpdateRequest
*************************************************/

// NoteUpdateRequest represents API parameter/response structure
type NoteUpdateRequest struct {
	Name    string `validate:"required"`
	Tags    []string
	IconID  types.ID `mapconv:"Icon.ID"`
	Class   string
	Content string
}

// Validate validates by field tags
func (o *NoteUpdateRequest) Validate() error {
	return validator.New().Struct(o)
}

// GetName returns value of Name
func (o *NoteUpdateRequest) GetName() string {
	return o.Name
}

// SetName sets value to Name
func (o *NoteUpdateRequest) SetName(v string) {
	o.Name = v
}

// GetTags returns value of Tags
func (o *NoteUpdateRequest) GetTags() []string {
	return o.Tags
}

// SetTags sets value to Tags
func (o *NoteUpdateRequest) SetTags(v []string) {
	o.Tags = v
}

// GetIconID returns value of IconID
func (o *NoteUpdateRequest) GetIconID() types.ID {
	return o.IconID
}

// SetIconID sets value to IconID
func (o *NoteUpdateRequest) SetIconID(v types.ID) {
	o.IconID = v
}

// GetClass returns value of Class
func (o *NoteUpdateRequest) GetClass() string {
	return o.Class
}

// SetClass sets value to Class
func (o *NoteUpdateRequest) SetClass(v string) {
	o.Class = v
}

// GetContent returns value of Content
func (o *NoteUpdateRequest) GetContent() string {
	return o.Content
}

// SetContent sets value to Content
func (o *NoteUpdateRequest) SetContent(v string) {
	o.Content = v
}

// convertTo returns naked NoteUpdateRequest
func (o *NoteUpdateRequest) convertTo() (*naked.Note, error) {
	dest := &naked.Note{}
	err := mapconv.ConvertTo(o, dest)
	return dest, err
}

// convertFrom parse values from naked NoteUpdateRequest
func (o *NoteUpdateRequest) convertFrom(naked *naked.Note) error {
	return mapconv.ConvertFrom(naked, o)
}

/*************************************************
* Switch
*************************************************/

// Switch represents API parameter/response structure
type Switch struct {
	ID             types.ID
	Name           string `validate:"required"`
	Description    string
	Tags           []string
	Icon           *naked.Icon `json:",omitempty"`
	CreatedAt      *time.Time
	ModifiedAt     *time.Time
	Zone           *naked.Zone `json:",omitempty"`
	NetworkMaskLen int         `mapconv:"UserSubnet.NetworkMaskLen" validate:"min=1,max=32"`
	DefaultRoute   string      `mapconv:"UserSubnet.DefaultRoute" validate:"ipv4"`
}

// Validate validates by field tags
func (o *Switch) Validate() error {
	return validator.New().Struct(o)
}

// GetID returns value of ID
func (o *Switch) GetID() types.ID {
	return o.ID
}

// SetID sets value to ID
func (o *Switch) SetID(v types.ID) {
	o.ID = v
}

// GetStringID gets value to StringID
func (o *Switch) GetStringID() string {
	return getStringID(o)
}

// SetStringID sets value to StringID
func (o *Switch) SetStringID(v string) {
	setStringID(o, v)
}

// GetInt64ID gets value to Int64ID
func (o *Switch) GetInt64ID() int64 {
	return getInt64ID(o)
}

// SetInt64ID sets value to Int64ID
func (o *Switch) SetInt64ID(v int64) {
	setInt64ID(o, v)
}

// GetName returns value of Name
func (o *Switch) GetName() string {
	return o.Name
}

// SetName sets value to Name
func (o *Switch) SetName(v string) {
	o.Name = v
}

// GetDescription returns value of Description
func (o *Switch) GetDescription() string {
	return o.Description
}

// SetDescription sets value to Description
func (o *Switch) SetDescription(v string) {
	o.Description = v
}

// GetTags returns value of Tags
func (o *Switch) GetTags() []string {
	return o.Tags
}

// SetTags sets value to Tags
func (o *Switch) SetTags(v []string) {
	o.Tags = v
}

// GetIcon returns value of Icon
func (o *Switch) GetIcon() *naked.Icon {
	return o.Icon
}

// SetIcon sets value to Icon
func (o *Switch) SetIcon(v *naked.Icon) {
	o.Icon = v
}

// GetCreatedAt returns value of CreatedAt
func (o *Switch) GetCreatedAt() *time.Time {
	return o.CreatedAt
}

// SetCreatedAt sets value to CreatedAt
func (o *Switch) SetCreatedAt(v *time.Time) {
	o.CreatedAt = v
}

// GetModifiedAt returns value of ModifiedAt
func (o *Switch) GetModifiedAt() *time.Time {
	return o.ModifiedAt
}

// SetModifiedAt sets value to ModifiedAt
func (o *Switch) SetModifiedAt(v *time.Time) {
	o.ModifiedAt = v
}

// GetZone returns value of Zone
func (o *Switch) GetZone() *naked.Zone {
	return o.Zone
}

// SetZone sets value to Zone
func (o *Switch) SetZone(v *naked.Zone) {
	o.Zone = v
}

// GetNetworkMaskLen returns value of NetworkMaskLen
func (o *Switch) GetNetworkMaskLen() int {
	return o.NetworkMaskLen
}

// SetNetworkMaskLen sets value to NetworkMaskLen
func (o *Switch) SetNetworkMaskLen(v int) {
	o.NetworkMaskLen = v
}

// GetDefaultRoute returns value of DefaultRoute
func (o *Switch) GetDefaultRoute() string {
	return o.DefaultRoute
}

// SetDefaultRoute sets value to DefaultRoute
func (o *Switch) SetDefaultRoute(v string) {
	o.DefaultRoute = v
}

// convertTo returns naked Switch
func (o *Switch) convertTo() (*naked.Switch, error) {
	dest := &naked.Switch{}
	err := mapconv.ConvertTo(o, dest)
	return dest, err
}

// convertFrom parse values from naked Switch
func (o *Switch) convertFrom(naked *naked.Switch) error {
	return mapconv.ConvertFrom(naked, o)
}

/*************************************************
* SwitchCreateRequest
*************************************************/

// SwitchCreateRequest represents API parameter/response structure
type SwitchCreateRequest struct {
	Name           string `validate:"required"`
	NetworkMaskLen int    `mapconv:"UserSubnet.NetworkMaskLen" validate:"min=1,max=32"`
	DefaultRoute   string `mapconv:"UserSubnet.DefaultRoute" validate:"ipv4"`
	Description    string
	Tags           []string
	IconID         types.ID `mapconv:"Icon.ID"`
}

// Validate validates by field tags
func (o *SwitchCreateRequest) Validate() error {
	return validator.New().Struct(o)
}

// GetName returns value of Name
func (o *SwitchCreateRequest) GetName() string {
	return o.Name
}

// SetName sets value to Name
func (o *SwitchCreateRequest) SetName(v string) {
	o.Name = v
}

// GetNetworkMaskLen returns value of NetworkMaskLen
func (o *SwitchCreateRequest) GetNetworkMaskLen() int {
	return o.NetworkMaskLen
}

// SetNetworkMaskLen sets value to NetworkMaskLen
func (o *SwitchCreateRequest) SetNetworkMaskLen(v int) {
	o.NetworkMaskLen = v
}

// GetDefaultRoute returns value of DefaultRoute
func (o *SwitchCreateRequest) GetDefaultRoute() string {
	return o.DefaultRoute
}

// SetDefaultRoute sets value to DefaultRoute
func (o *SwitchCreateRequest) SetDefaultRoute(v string) {
	o.DefaultRoute = v
}

// GetDescription returns value of Description
func (o *SwitchCreateRequest) GetDescription() string {
	return o.Description
}

// SetDescription sets value to Description
func (o *SwitchCreateRequest) SetDescription(v string) {
	o.Description = v
}

// GetTags returns value of Tags
func (o *SwitchCreateRequest) GetTags() []string {
	return o.Tags
}

// SetTags sets value to Tags
func (o *SwitchCreateRequest) SetTags(v []string) {
	o.Tags = v
}

// GetIconID returns value of IconID
func (o *SwitchCreateRequest) GetIconID() types.ID {
	return o.IconID
}

// SetIconID sets value to IconID
func (o *SwitchCreateRequest) SetIconID(v types.ID) {
	o.IconID = v
}

// convertTo returns naked SwitchCreateRequest
func (o *SwitchCreateRequest) convertTo() (*naked.Switch, error) {
	dest := &naked.Switch{}
	err := mapconv.ConvertTo(o, dest)
	return dest, err
}

// convertFrom parse values from naked SwitchCreateRequest
func (o *SwitchCreateRequest) convertFrom(naked *naked.Switch) error {
	return mapconv.ConvertFrom(naked, o)
}

/*************************************************
* SwitchUpdateRequest
*************************************************/

// SwitchUpdateRequest represents API parameter/response structure
type SwitchUpdateRequest struct {
	Name           string `validate:"required"`
	NetworkMaskLen int    `mapconv:"UserSubnet.NetworkMaskLen" validate:"min=1,max=32"`
	DefaultRoute   string `mapconv:"UserSubnet.DefaultRoute" validate:"ipv4"`
	Description    string
	Tags           []string
	IconID         types.ID `mapconv:"Icon.ID"`
}

// Validate validates by field tags
func (o *SwitchUpdateRequest) Validate() error {
	return validator.New().Struct(o)
}

// GetName returns value of Name
func (o *SwitchUpdateRequest) GetName() string {
	return o.Name
}

// SetName sets value to Name
func (o *SwitchUpdateRequest) SetName(v string) {
	o.Name = v
}

// GetNetworkMaskLen returns value of NetworkMaskLen
func (o *SwitchUpdateRequest) GetNetworkMaskLen() int {
	return o.NetworkMaskLen
}

// SetNetworkMaskLen sets value to NetworkMaskLen
func (o *SwitchUpdateRequest) SetNetworkMaskLen(v int) {
	o.NetworkMaskLen = v
}

// GetDefaultRoute returns value of DefaultRoute
func (o *SwitchUpdateRequest) GetDefaultRoute() string {
	return o.DefaultRoute
}

// SetDefaultRoute sets value to DefaultRoute
func (o *SwitchUpdateRequest) SetDefaultRoute(v string) {
	o.DefaultRoute = v
}

// GetDescription returns value of Description
func (o *SwitchUpdateRequest) GetDescription() string {
	return o.Description
}

// SetDescription sets value to Description
func (o *SwitchUpdateRequest) SetDescription(v string) {
	o.Description = v
}

// GetTags returns value of Tags
func (o *SwitchUpdateRequest) GetTags() []string {
	return o.Tags
}

// SetTags sets value to Tags
func (o *SwitchUpdateRequest) SetTags(v []string) {
	o.Tags = v
}

// GetIconID returns value of IconID
func (o *SwitchUpdateRequest) GetIconID() types.ID {
	return o.IconID
}

// SetIconID sets value to IconID
func (o *SwitchUpdateRequest) SetIconID(v types.ID) {
	o.IconID = v
}

// convertTo returns naked SwitchUpdateRequest
func (o *SwitchUpdateRequest) convertTo() (*naked.Switch, error) {
	dest := &naked.Switch{}
	err := mapconv.ConvertTo(o, dest)
	return dest, err
}

// convertFrom parse values from naked SwitchUpdateRequest
func (o *SwitchUpdateRequest) convertFrom(naked *naked.Switch) error {
	return mapconv.ConvertFrom(naked, o)
}

/*************************************************
* Zone
*************************************************/

// Zone represents API parameter/response structure
type Zone struct {
	ID           types.ID
	Name         string `validate:"required"`
	Description  string
	DisplayOrder int
	IsDummy      bool
	VNCProxy     *naked.VNCProxy  `json:",omitempty"`
	FTPServer    *naked.FTPServer `json:",omitempty"`
	Region       *naked.Region    `json:",omitempty"`
}

// Validate validates by field tags
func (o *Zone) Validate() error {
	return validator.New().Struct(o)
}

// GetID returns value of ID
func (o *Zone) GetID() types.ID {
	return o.ID
}

// SetID sets value to ID
func (o *Zone) SetID(v types.ID) {
	o.ID = v
}

// GetStringID gets value to StringID
func (o *Zone) GetStringID() string {
	return getStringID(o)
}

// SetStringID sets value to StringID
func (o *Zone) SetStringID(v string) {
	setStringID(o, v)
}

// GetInt64ID gets value to Int64ID
func (o *Zone) GetInt64ID() int64 {
	return getInt64ID(o)
}

// SetInt64ID sets value to Int64ID
func (o *Zone) SetInt64ID(v int64) {
	setInt64ID(o, v)
}

// GetName returns value of Name
func (o *Zone) GetName() string {
	return o.Name
}

// SetName sets value to Name
func (o *Zone) SetName(v string) {
	o.Name = v
}

// GetDescription returns value of Description
func (o *Zone) GetDescription() string {
	return o.Description
}

// SetDescription sets value to Description
func (o *Zone) SetDescription(v string) {
	o.Description = v
}

// GetDisplayOrder returns value of DisplayOrder
func (o *Zone) GetDisplayOrder() int {
	return o.DisplayOrder
}

// SetDisplayOrder sets value to DisplayOrder
func (o *Zone) SetDisplayOrder(v int) {
	o.DisplayOrder = v
}

// GetIsDummy returns value of IsDummy
func (o *Zone) GetIsDummy() bool {
	return o.IsDummy
}

// SetIsDummy sets value to IsDummy
func (o *Zone) SetIsDummy(v bool) {
	o.IsDummy = v
}

// GetVNCProxy returns value of VNCProxy
func (o *Zone) GetVNCProxy() *naked.VNCProxy {
	return o.VNCProxy
}

// SetVNCProxy sets value to VNCProxy
func (o *Zone) SetVNCProxy(v *naked.VNCProxy) {
	o.VNCProxy = v
}

// GetFTPServer returns value of FTPServer
func (o *Zone) GetFTPServer() *naked.FTPServer {
	return o.FTPServer
}

// SetFTPServer sets value to FTPServer
func (o *Zone) SetFTPServer(v *naked.FTPServer) {
	o.FTPServer = v
}

// GetRegion returns value of Region
func (o *Zone) GetRegion() *naked.Region {
	return o.Region
}

// SetRegion sets value to Region
func (o *Zone) SetRegion(v *naked.Region) {
	o.Region = v
}

// convertTo returns naked Zone
func (o *Zone) convertTo() (*naked.Zone, error) {
	dest := &naked.Zone{}
	err := mapconv.ConvertTo(o, dest)
	return dest, err
}

// convertFrom parse values from naked Zone
func (o *Zone) convertFrom(naked *naked.Zone) error {
	return mapconv.ConvertFrom(naked, o)
}
