// generated by 'github.com/sacloud/libsacloud/tools/internal/gen-api-structures'; DO NOT EDIT

package sacloud

// NakedNoteCreateRequest represents request parameter of Create API
type NakedNoteCreateRequest struct {
	Note *NakedNote `json:",omitempty"` // 対象リソース
}

// NakedNoteCreateResponse represents response of Create API
type NakedNoteCreateResponse struct {
	IsOk    bool       `json:"is_ok,omitempty"` // is_ok項目
	Success bool       `json:",omitempty"`      // success項目
	Note    *NakedNote `json:",omitempty"`      // 対象リソース
}

// NakedNoteReadResponse represents response of Read API
type NakedNoteReadResponse struct {
	IsOk    bool       `json:"is_ok,omitempty"` // is_ok項目
	Success bool       `json:",omitempty"`      // success項目
	Note    *NakedNote `json:",omitempty"`      // 対象リソース
}

// NakedNoteUpdateRequest represents request parameter of Update API
type NakedNoteUpdateRequest struct {
	Note *NakedNote `json:",omitempty"` // 対象リソース
}

// NakedNoteUpdateResponse represents response of Update API
type NakedNoteUpdateResponse struct {
	IsOk    bool       `json:"is_ok,omitempty"` // is_ok項目
	Success bool       `json:",omitempty"`      // success項目
	Note    *NakedNote `json:",omitempty"`      // 対象リソース
}

// NakedNoteDeleteResponse represents response of Delete API
type NakedNoteDeleteResponse struct {
	IsOk    bool `json:"is_ok,omitempty"` // is_ok項目
	Success bool `json:",omitempty"`      // success項目
}
